### ISSUE TITLE
how to use receive? can someone give a example ?

### ISSUE THREAD

**Issue by shshxy98** [thanos-io/thanos#1138]
how to use receive? can someone give a example ? thanks

**Comment by brancz** [comment]
The receive component is still in very active development hence I’d recommend to stay away from it until there are docs in place on how to use it (unless you are very closely following the development but even then it’s totally up to you). I say this because only very few pieces of the original design doc have actually already been implemented. We are actively working on pushing this forward, if you are interested I’d recommend you follow https://github.com/improbable-eng/thanos/issues/1093. I’d suggest we leave this issue open as a place for user feedback once we do put documentation in place to discuss separately from the umbrella doc what aspects users want to see more detail on.

**Comment by Ghostbaby** [comment]
1. you need a storage cluster,(opentsdb/kafka)
2. you need to a adapter for the storage cluster,
3. you need to edit the Prometheus ,add this items to the yaml
`  remoteWrite:
  - url: http://prometheus-kafka-adapter-svc:8080/receive`

**Comment by brancz** [comment]
The thanos receive component is implementing the storage and API (what you describe as adapter) natively in Thanos.

**Comment by e9169** [comment]
Hi. So, to summarize and get up to date with this, is the receive component ready to use? If yes, does this replace another current or past functionality? I can't find documentation on this. Is the use of receive mandatory or optional as of today?

Thank you for your information and help.

**Comment by brancz** [comment]
It's totally optional, you can and will continue to be able to use Thanos completely without it. When it's completely done (which it's not completely as shown in the umbrella issue), then you will be able to make a trade-off of either using the Thanos sidecar and requiring the Thanos querier to have direct access to Prometheus servers, or allow a Prometheus server to replicate data to the Thanos receive component. There are trade-offs to both sides for sure and we'll be documenting these appropriately, just haven't gotten around to it yet as some of it would be confusing without all functionality implemented :slightly_smiling_face:.

**Comment by GuyCheung** [comment]
I thought about why I wanted to use receive but not sidecar a long time, I think the most important thing is I can get replicated data in seconds delay, which means can assume the Prometheus as a stateless component just scrape data. when the Prometheus node dead, just try to failover scrape targets to other node but not try to recover the dead node asap.

when I used sidecar before, I still have no ideas of how to resolve the Prometheus node dead problem

**Comment by brancz** [comment]
Closing as multiple examples have been given. Note receive is still in experimental state but we are pretty close to finishing everything described in the original design doc.
