### ISSUE TITLE
Thanos Compact should check before compacting if there's enough space 

### ISSUE THREAD

**Issue by GiedriusS** [thanos-io/thanos#1152]
I'm not sure if this is possible ATM but it would be a nice thing to have: Thanos Compact could check if there's enough space on disk to perform compaction before trying to download everything (those blocks could be around ~100GiB) and trying to compact.

Investigate this and, if possible, implement.

**Comment by jjneely** [comment]
[meta.json.txt](https://github.com/improbable-eng/thanos/files/3188863/meta.json.txt)

Large blocks are a thing.  This is from a Prometheus VM doing 2.65 million metrics in the head block and about 135k samples/s -- which is not completely scary.  I'm looking for a way to forcast how much scratch space I need, or compact to behave better when it knows that it cannot further compact a set of blocks due to scratch space limitations.

**Comment by brancz** [comment]
Are you thinking storage scheduling or why are you labeling this with `difficulty: hard`?

**Comment by bwplotka** [comment]
I think it's hard because it's hard to estimate the size in theory. However checking sizes of source blocks would already give you quite precise the overall size needed IMO, so I would say at the size will be most likely 
Max: `all source blocks sizes x 2`
Min: `all source blocks + size of biggest source block`

We chould easily check if at least `min` size can fit. and halt/crash/increment/continue with other compaction/inc metric otherwise. This simple thing is `difficulty: easy` (:

**Comment by GiedriusS** [comment]
Indeed, we should check if the `tsdb` package provides the functionality to calculate the exact size of the resulting blocks since it depends on the data itself. If that is not possible, I agree: it should be completely fine to add those simple checks as a heuristic. 😄

**Comment by brancz** [comment]
Exactly my thought, just wanted to make sure I’m not totally missing something.

**Comment by brancz** [comment]
I believe this is in progress no? @GiedriusS

**Comment by GiedriusS** [comment]
Yes :+1: waiting for a review on https://github.com/thanos-io/thanos/pull/1550 which should solve this issue.

**Comment by GiedriusS** [comment]
Still in progress, just didn't have much time.

**Comment by GiedriusS** [comment]
Still want to finish this soon.

**Comment by GiedriusS** [comment]
Will probably get back to this in the next couple of weeks because I have free time now.

**Comment by bwplotka** [comment]
Awesome!

**Comment by GiedriusS** [comment]
I started something but haven't finished. I think this is still relevant.
