### ISSUE TITLE
Should irate use the counter aggregation?

### ISSUE THREAD

**Issue by alfred-landrum** [thanos-io/thanos#1317]
In the query package, function `aggrsFromFunc` selects the aggregation to use based on the function hint from the selection parameters.

It chooses the counter aggregation for `rate` and `increase`. Should it do so for `irate` as well?

**Comment by GiedriusS** [comment]
Hi, probably not since the "last true sample" is appended at the "counter" aggregation and `irate` operates on the last samples in each time window. However, I'd be gladly proven wrong - please feel free to add another test case here https://github.com/improbable-eng/thanos/blob/master/pkg/query/querier_test.go#L45. Also, please feel free to add some comments  or refactor around that part in the code if it feels ununderstandable

**Comment by GiedriusS** [comment]
Deleted my last message since it was wrong.

Actually, I have looked into it and the answer is "probably not". Let me explain. In the default case, as it is right now, we ask for the aggregated count and average data. Let's say we ask for `irate(foo[10m])` so that the data would encompass at least two different samples. At each step, we would calculate the average since the original data is no longer there. There are two options here: we could only take *one* sample every 5 minutes and pretend that it is the one and only true value of that 5m window, or we could calculate the average from all of the original samples in the 5m window. Thanos, as it is right now, takes the 2nd option. Then, once `irate` gets this data it operates on the first and last points that it is provided.

The counter aggregation does something different: it is essentially a counter of all the values in a specified time window. With `rate` and `increase` it is OK to use that because, first of all, `rate` underneath uses `increase`, and `increase`, obviously, calculates how much a time series value has increased over the specified time range - which is what the counter aggregation is doing exactly.

**Comment by alfred-landrum** [comment]
Thanks for the response! I'm sorry, but I didn't follow the rationale for why using the average would be preferable.

If it's helpful, here's a little more context on why I ask, maybe you could point out if I'm misunderstanding something:
- The irate implementation (function instantValue in the promql package) calculates a difference in value expecting that the series is a counter, an increasing sequence with possible resets.
- If the counter aggregation is selected for downsampled data, then CounterSeriesIterator, generating an increasing sequence from the aggregated counter state & last raw value.
- Since the promql implementation for irate expects a counter-like sequence, it should use that aggregation, like rate & increase. If it uses the average, resets in the series will make the irate difference calculation inaccurate.

I think there are 4 functions in promql that expect to be run on counters: rate, increase, irate, delta, resets. I hadn't considered delta or resets when I posted this question. I think the same rationale applies for delta as well, that it too should use the counter aggregation type. As for resets, the current downsampling for counters doesn't record the number of resets within a downsampled interval, so I think resets is only useful on raw values, not on downsampled ones.

**Comment by GiedriusS** [comment]
Hmm, perhaps you are correct. Care to convert this into a test case and make a PR? I would be very grateful. It should probably go here: https://github.com/thanos-io/thanos/blob/2c5f2cde11f5cd100f147ad2e5d4dbeccbd604c5/pkg/query/querier_test.go#L45.
