### ISSUE TITLE
Thanos receive failing on receive "out of order sample"

### ISSUE THREAD

**Issue by R4scal** [thanos-io/thanos#1509]
thanos, version 0.7.0 (branch: HEAD, revision: c6eaf68bec32aefd280318eaef6121d6ddb20d10)

prometheus, version 2.12.0 (branch: HEAD, revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86)

**Setup**
prometheus (in kubernetes) + influxdb_exporter + thanos receive

**What happened**
1. In prometheus logs (1 record on 30-60 seconds with scrape every 15 seconds)
```
{"caller":"scrape.go:1164","component":"scrape manager","level":"warn","msg":"Error on ingesting out-of-order samples","num_dropped":11,"scrape_pool":"influxdb_exporters","target":"http://1.1.1.1:xxx/metrics","ts":"2019-09-11T07:58:16.910Z"}
```
2. In thanos receive logs (thouthands)
```
{"caller":"handler.go:307","component":"receive-handler","endpoint":"http://2.2.2.2:xxx/api/v1/receive","err":"failed to non-fast add: out of order sample","level":"error","msg":"storing locally","ts":"2019-09-11T07:59:37.697039374Z"}
```
3. After some time in prometheus logs
```
{"caller":"queue_manager.go:716","component":"remote","count":100,"err":"context canceled","level":"error","msg":"non-recoverable error","queue":"0:http://2.2.2.2:xxx/api/v1/receive","ts":"2019-09-11T08:10:04.482Z"}
```
In this scenario, the load on the processor and the network also increases significantly, since prometheus tries many times to send the same data

**What you expected to happen**
I think, need reproduce prometheus action, when receive "out of order sample" it's warning, not critical error, need drop this sample (with increment dropped metrics counter) and response 200 to write request

**Comment by krasi-georgiev** [comment]
In general the problem here seems to be that the `influxdb_exporter` is misbehaving and adds incorrect timestamps.

@R4scal your suggestion would work, but a better solution would be to not even try to send these out of order samples in the first place. cc @cstyan @csmarchbanks 

@squat  tsdb has the error `tsdb.ErrOutOfOrderSample` so can also add this as a fail safe. Can match against that error,log a warning and just return 200 response. What do you think?

**Comment by squat** [comment]
@krasi-georgiev Ack sounds good to me. I can make the PR quickly

**Comment by csmarchbanks** [comment]
What error code does Thanos return when failing due to an out of order error? Prometheus should only retry on 5XX errors, so returning a 4XX would probably be the correct behavior and avoid the retries.

Not sure exactly how the out of order is happening, Prometheus should process samples in order for each series, but there could be a bug somewhere. I am not very familiar with the Thanos remote write receiver, but does it return out of order for samples with the same timestamp as a previous one? Or just when they are actually out of order?

**Comment by squat** [comment]
When writing to disk returns an error, the replication routine understands that the time series weren’t successfully replicated and returns a 500. Today replication is either successful (it meets the threshold) and returns a 200 or its not and returns a 500. It sounds like we need to bubble up another value which indicates metric validity.

**Comment by krasi-georgiev** [comment]
@csmarchbanks I would say that these out of order samples shouldn't even end up in the WAL and than shouldn't be sent via remote write either.

**Comment by csmarchbanks** [comment]
Yes, I agree that Prometheus should not send them in the first place, I think I skimmed the issue too quickly the first time and didn't notice the error from Prometheus itself :). I will look into a fix for that soon. Thanos should still return a 4XX for older Prometheus instances sending incorrect data to avoid retry loops.

I occasionally see out of order timestamp errors going into Cortex as well, but no logs from Prometheus, so it is possible that other errors can cause out of orders.

**Comment by krasi-georgiev** [comment]
agreed :+1:

**Comment by brancz** [comment]
Returning 409 (conflict) sounds reasonable.
