### ISSUE TITLE
Thanos query partial response defaults to true

### ISSUE THREAD

**Issue by dtrejod** [thanos-io/thanos#1576]
The `query.partial-response` flag under the thanos queries defaults to true. Should the default  be switched to false to keep inline with the flag description? 

https://github.com/thanos-io/thanos/blob/ae45e279dd06364406771f25715f935ad0245aeb/cmd/thanos/query.go#L97-L98

There is otherwise no order way to disable partial responses.

**Comment by jojohappy** [comment]
Hi, I think we need to enable `partial response` as default, because of distributed architecture and some storeAPIs. If you want to disable `partial response`, you can use one of methods below:
* set `query.partial-response` to false.
* do not check the `partial response` check-box in Query UI.
* If you use query api, add `partial_response=false` into query parameter, e.g. `/api/v1/query?query=up&dedup=true&partial_response=false&time=1569567441.836`

**Comment by dtrejod** [comment]
Forgot you need the `no` prefix to negate a kingpin.v2 bool flag.  `--no-query.partial-response`. 

Thanks!
