### ISSUE TITLE
Range query is extreamly slow when time range is large

### ISSUE THREAD

**Issue by benamazing** [thanos-io/thanos#1875]
Hi, I'm using thanos 0.9 for global view of 2 prometheus at backend.

For a range query, when the time range is small (e.g, last 24 hours), the response time of thanos query is almost as good as original prometheus. However, when the time range is large (e.g, last 3 months), the query response time would become extreamly long. 

For instance, for the same query:

```
promql: avg (irate(node_cpu_seconds_total{instance="host1:9100",job="node",mode="user"}[5m]))
step: 21600
time range: 6 months
```

If I directly query the two backend prometheus respectively, the response time would be around only **1 second**. But if i query with the thanos query, the response time would be **20+ seconds**, which is unacceptable.

I tried to turn on debug log for tracing, got it as below:

```
### thanos query log
level=debug ts=2019-12-12T02:04:04.613112629Z caller=proxy.go:265 msg="store Addr: sidecar1:10901 LabelSets: [name:\"function\" value:\"sre\" ,name:\"prom_id\" value:\"prom1\" ] Mint: -62167219200000 Maxt: 9223372036854775807 queried;store Addr: sidecar2:10901 LabelSets: [name:\"function\" value:\"sre\" ,name:\"prom_id\" value:\"prom2\" ] Mint: -62167219200000 Maxt: 9223372036854775807 queried"

### thanos sidecar1 log
level=debug ts=2019-12-12T02:04:14.314769717Z caller=prometheus.go:199 msg="started handling ReadRequest_SAMPLED response type."
level=debug ts=2019-12-12T02:04:24.089423045Z caller=prometheus.go:242 msg="handled ReadRequest_SAMPLED request." series=224

### thanos sidecar2 log
level=debug ts=2019-12-12T02:04:15.871552485Z caller=prometheus.go:199 msg="started handling ReadRequest_SAMPLED response type."
level=debug ts=2019-12-12T02:04:24.036981523Z caller=prometheus.go:242 msg="handled ReadRequest_SAMPLED request." series=672
```

From the log, thanos query received the query request on **"02:04:04"**, but not passing the request to sidecar until **"02:04:14"**. What did the thanos query component do during the 10 seconds period? And each sidecar cost almost 10 seconds to retrive the data from prometheus, it seems quite slow as well.

Is there any way I can tune the performance?

**Comment by daixiang0** [comment]
Have you call "compact" to do downstampling? Details refer to [doc](https://github.com/thanos-io/thanos/blob/master/docs/components/compact.md).

**Comment by benamazing** [comment]
> Have you call "compact" to do downstampling? Details refer to [doc](https://github.com/thanos-io/thanos/blob/master/docs/components/compact.md).

No, i dont plan to use object storage, i just used the sidecar to combine multiple prometheus' data for global view.

**Comment by vermaabhay** [comment]
"High load on all prometheus nodes due to query fanout from thanos querier"

We have implemented just the querier and sidecar component of thanos, to enable HA(fill gaps in grafana dashboards) for a 2 node prometheus. Earlier, we were executing a very heavy query, hence the load was considerably high on one of the prometheus node at a time. Now querier fanouts the query to both the sidecars (nodes) and it is creating similar high load on both the nodes compared to what was on just one at a time.

Also, we have increased the cpu cores to tackle to problem but it isn't helping. Any leads will be highly appreciated.

prometheus, version 2.13.0
thanos, version 0.8.1

**Comment by valyala** [comment]
@vermaabhay , try querying Prometheus HA pair with [Promxy](https://github.com/jacksontj/promxy).

**Comment by bwplotka** [comment]
@valyala how is your response helpful for anyone (: Do you want us to comment on every Victoria Metric bug or missing feature, "hey don't bother, just use another product X"? 😃 It was old comment as well but still... (: 

Anyway @benamazing depending on the cardinality, scrape interval. and how compacted your blocks are (I hope you enabled compaction on Prometheus) this is known bug and will be solved with https://github.com/prometheus/prometheus/pull/5882 which is actively worked on now. The issue was API limitation which requires Prometheus to decode/encode chunks for no reason. (: Hopefully should be fixed in next Prometheus release!
