### ISSUE TITLE
sidecar: fails to upload on Windows

### ISSUE THREAD

**Issue by Lightn** [thanos-io/thanos#2016]
**Thanos, Prometheus and Golang version used**:
Thanos:
Version	0.10.0
Revision	698c7a922cd5dcaa53e305db5c2adb4e79d328ba
Branch	HEAD
BuildUser	root@b1b9ee0e47e5
BuildDate	20200113-14:40:25
GoVersion	go1.13.1

Prometheus:
Version	2.15.2
Revision	d9613e5c466c6e9de548c4dae1b9aabf9aaf7c57
Branch	HEAD
BuildUser	root@688433cf4ff7
BuildDate	20200106-15:06:47
GoVersion	go1.13.5

**Object Storage Provider**:
FILESYSTEM

**What happened**:
Sidecar is unable to read Prometheus upload data chunks to write to storage.

**What you expected to happen**:
Sidecar should upload chunks.

**How to reproduce it (as minimally and precisely as possible)**:
Prometheus is running directly on Windows. I am not using containers.  I am trying to add Thanos for long term storage, but the sidecar is unable to read the chunks in the Prometheus directory.  It looks like prometheus.exe is holding onto the files and preventing them from being read by Thanos.

**Full logs to relevant components**:
<details>Logs
<p>
level=info ts=2020-01-16T21:00:18.5934785Z caller=shipper.go:349 msg="upload new block" id=01DYPS9CRNCFN40GX2CNXZEV90
level=error ts=2020-01-16T21:00:18.5944801Z caller=shipper.go:316 msg="shipping failed" block=01DYPS9CRNCFN40GX2CNXZEV90 err="clean upload directory: remove C:\\UTIL\\prometheus\\data\\thanos\\upload\\01DYPS9CRNCFN40GX2CNXZEV90\\chunks\\000001: The process cannot access the file because it is being used by another process."
level=info ts=2020-01-16T21:00:18.5944801Z caller=shipper.go:349 msg="upload new block" id=01DYQ0540QF0XH7BB7VXPZBP1B
level=error ts=2020-01-16T21:00:18.595479Z caller=shipper.go:316 msg="shipping failed" block=01DYQ0540QF0XH7BB7VXPZBP1B err="clean upload directory: remove C:\\UTIL\\prometheus\\data\\thanos\\upload\\01DYQ0540QF0XH7BB7VXPZBP1B\\chunks\\000001: The process cannot access the file because it is being used by another process."
level=info ts=2020-01-16T21:00:18.595479Z caller=shipper.go:349 msg="upload new block" id=01DYQ70V7MTB9NQ3Y9FD6E0Z2R
level=error ts=2020-01-16T21:00:18.595479Z caller=shipper.go:316 msg="shipping failed" block=01DYQ70V7MTB9NQ3Y9FD6E0Z2R err="clean upload directory: remove C:\\UTIL\\prometheus\\data\\thanos\\upload\\01DYQ70V7MTB9NQ3Y9FD6E0Z2R\\chunks\\000001: The process cannot access the file because it is being used by another process."
level=info ts=2020-01-16T21:00:18.5964801Z caller=shipper.go:349 msg="upload new block" id=01DYQDWJ7E5WJZ0368X9D2AEZ2
level=error ts=2020-01-16T21:00:18.5964801Z caller=shipper.go:316 msg="shipping failed" block=01DYQDWJ7E5WJZ0368X9D2AEZ2 err="clean upload directory: remove C:\\UTIL\\prometheus\\data\\thanos\\upload\\01DYQDWJ7E5WJZ0368X9D2AEZ2\\chunks\\000001: The process cannot access the file because it is being used by another process."
level=info ts=2020-01-16T21:00:18.5964801Z caller=shipper.go:349 msg="upload new block" id=01DYQMR8S7W88BJ7MGFEFAJYEY
level=error ts=2020-01-16T21:00:18.5974799Z caller=shipper.go:316 msg="shipping failed" block=01DYQMR8S7W88BJ7MGFEFAJYEY err="clean upload directory: remove C:\\UTIL\\prometheus\\data\\thanos\\upload\\01DYQMR8S7W88BJ7MGFEFAJYEY\\chunks\\000001: The process cannot access the file because it is being used by another process."
level=info ts=2020-01-16T21:00:18.5974799Z caller=shipper.go:349 msg="upload new block" id=01DYQVM0RE7B0P1DPZ6ETN5B2A
level=error ts=2020-01-16T21:00:18.5984792Z caller=shipper.go:316 msg="shipping failed" block=01DYQVM0RE7B0P1DPZ6ETN5B2A err="clean upload directory: remove C:\\UTIL\\prometheus\\data\\thanos\\upload\\01DYQVM0RE7B0P1DPZ6ETN5B2A\\chunks\\000001: The process cannot access the file because it is being used by another process."
level=info ts=2020-01-16T21:00:18.5984792Z caller=shipper.go:349 msg="upload new block" id=01DYR2FQY3S4H6PFR6B23W5RQS
level=error ts=2020-01-16T21:00:18.6074808Z caller=shipper.go:364 msg="failed to clean upload directory" err="remove C:\\UTIL\\prometheus\\data\\thanos\\upload\\01DYR2FQY3S4H6PFR6B23W5RQS\\chunks\\000001: The process cannot access the file because it is being used by another process."
level=error ts=2020-01-16T21:00:18.6074808Z caller=shipper.go:316 msg="shipping failed" block=01DYR2FQY3S4H6PFR6B23W5RQS err="upload chunks: upload file C:\\UTIL\\prometheus\\data\\thanos\\upload\\01DYR2FQY3S4H6PFR6B23W5RQS\\chunks\\000001 as 01DYR2FQY3S4H6PFR6B23W5RQS\\chunks\\C:\\UTIL\\prometheus\\data\\thanos\\upload\\01DYR2FQY3S4H6PFR6B23W5RQS\\chunks\\000001: mkdir C:\\UTIL\\thanos\\data\\01DYR2FQY3S4H6PFR6B23W5RQS\\chunks\\C:: The filename, directory name, or volume label syntax is incorrect."
level=warn ts=2020-01-16T21:00:18.6084814Z caller=sidecar.go:315 err="failed to sync 7 blocks" uploaded=0
</p>
</details>

**Environment**:
- OS: Windows Server 2012 R2
- Prometheus command line: --storage.tsdb.retention.time=30d --web.enable-lifecycle --web.enable-admin-api --storage.tsdb.min-block-duration=2h --storage.tsdb.max-block-duration=2h
- Thanos command line: sidecar --tsdb.path C:\UTIL\prometheus\data\ --prometheus.url http://localhost:9090 --http-address 0.0.0.0:19191 --grpc-address 0.0.0.0:19090 --objstore.config-file bucket_config.yaml
- bucket_config.yaml
```
type: FILESYSTEM
config:
  directory: 'C:\UTIL\thanos\data'
```

**Comment by daixiang0** [comment]
@Lightn hi, seems there are 2+ processes do actions:
```
caller=shipper.go:316 msg="shipping failed" block=01DYQMR8S7W88BJ7MGFEFAJYEY err="clean upload directory: remove C:\\UTIL\\prometheus\\data\\thanos\\upload\\01DYQMR8S7W88BJ7MGFEFAJYEY\\chunks\\000001: The process cannot access the file because it is being used by another process." level=info ts=2020-01-16T21:00:18.5974799Z caller=shipper.go:349 msg="upload new block" id=01DYQVM0RE7B0P1DPZ6ETN5B2A level=error ts=2020-01-16T21:00:18.5984792Z caller=shipper.go:316 msg="shipping failed" block=01DYQVM0RE7B0P1DPZ6ETN5B2A err="clean upload directory: remove C:\\UTIL\\prometheus\\data\\thanos\\upload\\01DYQVM0RE7B0P1DPZ6ETN5B2A\\chunks\\000001: The process cannot access the file because it is being used by another process."
```

Could you reboot and then make sure only one prometheus and one thanos alive?

**Comment by jeffbstewart** [comment]
I'm seeing the same symptom.  Blocks are not uploading because the "clean upload directory" step can't remove the file.  It can't remove the file because prometheus is holding the file open.  SysInternals Process Explorer verifies prometheus holds the file open, as does trying to delete the file from the Windows Explorer.  It reports that prometheus.exe has the file open.

from the logs (this repeats every 30 seconds)
level=info ts=2021-03-11T22:34:27.9704238Z caller=shipper.go:334 msg="upload new block" id=01F0HNQV2ZMVZ9ZJG2BJRRE84H
level=warn ts=2021-03-11T22:34:27.9734202Z caller=sidecar.go:275 err="upload 01F0HNQV2ZMVZ9ZJG2BJRRE84H: clean upload directory: remove c:\\Prometheus\\data\\thanos\\upload\\01F0HNQV2ZMVZ9ZJG2BJRRE84H\\chunks\\000001: Access is denied." uploaded=0

Exactly one copy of prometheus running on the system (Windows 10, no containerization, though it is running as a service under nssm), one copy of thanos sidecar (running in a command shell for now while I figure this out).  My bucket_config.yaml matches Lightn's, (though my directory is c:\prometheus\data).

I suspect this is a Windows file vs. Unix file semantics.  Unix is perfectly happy to unlink open files.  Windows is not.  So we either need to get prometheus to close that file reference, decide we can wait until a reboot to delete it (using the MoveFileEx API), or tolerate this file remaining and just upload the block.

Is anyone successfully using the sidecar to upload blocks from a Windows host?  I suspect anyone trying to setup the side car on windows 10 will run into this.

**Comment by Lightn** [comment]
Could this be re-opened?  I am seeing the same thing on the latest version 0.23.1.  This time I tried it with S3 storage via minio.  
The problem is as jeffbstewart says.

**Comment by lholland421** [comment]
+1 We are seeing this exact issue too. We are running a single prometheus instance on a windows host using NSSM and a single instance of Thanos. 
I can see in the logs that thanos is not able to cleanup the upload directory and therefore fails to upload the chunks. 
`"The process cannot access the file because it is being used by another process."`
