### ISSUE TITLE
Add support for max-time in sidecar

### ISSUE THREAD

**Issue by omerlh** [thanos-io/thanos#2029]
Currently, the sidecar does not support `max-time` settings - it is always maximum. We have a use case where we need it - we want to migrate from centralized Prometheus (using federation) to thanos. For the migration period, I was thinking that we can run the sidecar on centralized prometheus with `max-time` set to the time where we started Thanos - so old data will be served from this sidecar, and new data from thanos. The only missing bit is this setting. Does adding it makes sense?

**Comment by GiedriusS** [comment]
This is probably more involved than it sounds. We set the max time currently to `math.MaxInt64` due to the fact that we don't want to depend on the results of the Info() gRPC calls since it happens periodically and we use that information to determine where to send the query. Hence, it is set to that value at the moment because Prometheus is always adding new information.

**Comment by bwplotka** [comment]
@omerlh Why you cannot ask both? You can totally hook both centralized Prometheus + sidecar AND new Thanos in a way that even if BOTH will respond with data it will be deduplicated into one. This is because samples should be exactly the same. (: 

So there will be some duplication of effort (as you will fetch from both), but functionally it will work just fine.

**Comment by omerlh** [comment]
Yeah, that what I ended up doing - adding `prometheus_replica` as external label, that solved it with deduplication as you suggested. But, as the data on this Prometheus is static (one Thanos is production, we're going to stop federation and relay on Thanos, and keep this one for historic data) .- I though this could save a huge amount of dedupe, as most queries will not go to there.

BTW I'm aware that the sidecar can scarpe and upload old data, but it marked as experimental...

**Comment by bwplotka** [comment]
> BTW I'm aware that the sidecar can Scarpe and upload old data, but it marked as experimental...

Where?

**Comment by omerlh** [comment]
In the docs: https://github.com/thanos-io/thanos/blob/master/docs/components/sidecar.md#upload-compacted-blocks-experimental

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
