### ISSUE TITLE
thanos compact crashed on start

### ISSUE THREAD

**Issue by omerlh** [thanos-io/thanos#2092]
**Thanos, Prometheus and Golang version used**: quay.io/thanos/thanos:v0.9.0

**Object Storage Provider**: AWS S3

**What happened**: 
Bucket crash on start without any indicative error:

```
level=info ts=2020-02-03T12:21:05.305147118Z caller=main.go:149 msg="Tracing will be disabled"
level=info ts=2020-02-03T12:21:05.305441306Z caller=factory.go:43 msg="loading bucket configuration"
level=info ts=2020-02-03T12:21:05.39996649Z caller=prober.go:127 msg="changing probe status" status=healthy
level=info ts=2020-02-03T12:21:05.400002811Z caller=http.go:53 service=http/server component=bucket msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2020-02-03T12:21:05.406950762Z caller=bucket.go:410 msg="synchronizing block metadata"
level=info ts=2020-02-03T12:21:12.936537836Z caller=bucket.go:430 msg="downloaded blocks meta.json" num=376
level=info ts=2020-02-03T12:23:04.867262419Z caller=main.go:205 msg="caught signal. Exiting." signal=terminated
level=info ts=2020-02-03T12:23:04.867372231Z caller=http.go:78 service=http/server component=bucket msg="internal server shutdown" err=null
level=info ts=2020-02-03T12:23:04.867397145Z caller=prober.go:137 msg="changing probe status" status=not-healthy reason=null
level=info ts=2020-02-03T12:23:04.867423188Z caller=main.go:197 msg=exiting
```

**What you expected to happen**:
Bucket started correctly

**How to reproduce it (as minimally and precisely as possible)**:
Deploy bucket with AWS s3 config

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by GiedriusS** [comment]
Hi, what command did you run exactly? Are you sure that the process hasn't received any signal which made it terminate according to the logs?

Could you try the `master` version to see if it is still reproducible?

**Comment by flashick** [comment]
Hello!

I have the same error, but before that it successfully done downsampling. It seems like compactor has done downsampling and kill itself because everything is done ¯\_(ツ)_/¯:
`...
level=info ts=2020-02-04T14:08:02.649925407Z caller=clean.go:25 msg="started cleaning of aborted partial uploads"
level=info ts=2020-02-04T14:08:02.737468321Z caller=fetcher.go:364 component=block.MetaFetcher msg="successfully fetched block metadata" duration=87.477851ms cached=14 returned=14 partial=0
level=info ts=2020-02-04T14:08:02.73775208Z caller=clean.go:50 msg="cleaning of aborted partial uploads done"
level=warn ts=2020-02-04T14:08:02.737859803Z caller=intrumentation.go:58 msg="changing probe status" status=not-ready reason=null
level=info ts=2020-02-04T14:08:02.738015045Z caller=http.go:81 service=http/server component=compact msg="internal server shutdown" err=null
level=info ts=2020-02-04T14:08:02.738102828Z caller=intrumentation.go:70 msg="changing probe status" status=not-healthy reason=null
level=info ts=2020-02-04T14:08:02.738197582Z caller=main.go:200 msg=exiting
level=debug ts=2020-02-04T14:08:02.738282585Z caller=main.go:104 msg="maxprocs: No GOMAXPROCS change to reset%!(EXTRA []interface {}=[])"`

Full log: https://gist.github.com/flashick/64766db55c8cac54bd04cd053e9b12ea

Command:
`/bin/thanos compact --data-dir /data/compact-tmp --objstore.config-file=/etc/thanos/bucket_config.yaml --retention.resolution-raw=180d --retention.resolution-5m=180d --retention.resolution-1h=180d --log.level=debug`
I have tried two images: quay.io/thanos/thanos:master-2019-11-26-825f1199 and quay.io/thanos/thanos:master-2020-02-04-7c02430c

**Comment by GiedriusS** [comment]
It looks like we have two different cases:
* @omerlh in your case Thanos Compact receives a signal for some reason. Could you please upload the full log? Maybe perhaps you are running in k8s with some weird readiness/healthiness probe? 
* @flashick AFAICT that is exactly what is happening. Not sure on how to improve the log messages there besides the fact that the last one looks like it has a bit of garbage in it. The exit code, though, is `0`, right?

**Comment by bwplotka** [comment]
Are you aware of `--wait` flag?

**Comment by omerlh** [comment]
I used kube-thanos for deploying the bucket, didn't changed anything. I looked, there is nothing more in the logs and it doesn't look like it crash becuase of memory issues.

**Comment by kakkoyun** [comment]
@omerlh In your case, this could be related to readiness checks from `kube-thanos`. As far as I can tell from your logs that it proceeds to the ready state. Try adjusting your readiness values.

https://github.com/thanos-io/kube-thanos/blob/c1c7294db937a59b7c3f071ed03048f8a397a16d/jsonnet/kube-thanos/kube-thanos-compact.libsonnet#L77-L81

**Comment by saumyasah** [comment]
> Hello!
> 
> 
> 
> I have the same error, but before that it successfully done downsampling. It seems like compactor has done downsampling and kill itself because everything is done ¯\_(ツ)_/¯:
> 
> Object Storage Provider: ceph S3
> 
> ```
> 
> ...
> 
> level=info ts=2020-02-04T14:08:02.649925407Z caller=clean.go:25 msg="started cleaning of aborted partial uploads"
> 
> level=info ts=2020-02-04T14:08:02.737468321Z caller=fetcher.go:364 component=block.MetaFetcher msg="successfully fetched block metadata" duration=87.477851ms cached=14 returned=14 partial=0
> 
> level=info ts=2020-02-04T14:08:02.73775208Z caller=clean.go:50 msg="cleaning of aborted partial uploads done"
> 
> level=warn ts=2020-02-04T14:08:02.737859803Z caller=intrumentation.go:58 msg="changing probe status" status=not-ready reason=null
> 
> level=info ts=2020-02-04T14:08:02.738015045Z caller=http.go:81 service=http/server component=compact msg="internal server shutdown" err=null
> 
> level=info ts=2020-02-04T14:08:02.738102828Z caller=intrumentation.go:70 msg="changing probe status" status=not-healthy reason=null
> 
> level=info ts=2020-02-04T14:08:02.738197582Z caller=main.go:200 msg=exiting
> 
> level=debug ts=2020-02-04T14:08:02.738282585Z caller=main.go:104 msg="maxprocs: No GOMAXPROCS change to reset%!(EXTRA []interface  {}=[])"
> 
> ```
> 
> 
> 
> Full log: https://gist.github.com/flashick/64766db55c8cac54bd04cd053e9b12ea
> 
> 
> 
> Command:
> 
> ```
> 
> /bin/thanos compact --data-dir /data/compact-tmp --objstore.config-file=/etc/thanos/bucket_config.yaml --retention.resolution-raw=180d --retention.resolution-5m=180d --retention.resolution-1h=180d --log.level=debug
> 
> ```
> 
> I have tried two images: quay.io/thanos/thanos:master-2019-11-26-825f1199 and quay.io/thanos/thanos:master-2020-02-04-7c02430c

I have the same error. 

Error log:
```

https://gist.github.com/saumyasah/9a0b5182055c9022ee7e73d3b17f4866

```

Command 

```

export GOMAXPROCS=$(nproc)
thanos compact \
   --data-dir /var/lib/thanos/compact \
   --objstore.config-file /usr/local/bin/local-objstore.yml \
   --retention.resolution-raw 30d \
   --retention.resolution-5m 90d \
   --retention.resolution-1h 1y \
   --log.level debug

```

**Comment by yeya24** [comment]
@saumyasah can you add `--wait` and try again?

**Comment by saumyasah** [comment]
> @saumyasah can you add `--wait` and try again?

Yes it worked thank you so much
