### ISSUE TITLE
Ability to mine data directly from block storage

### ISSUE THREAD

**Issue by maulikjs** [thanos-io/thanos#2251]
Hey Folks,
So we have an interesting use case, we have all these valuable metrics data, instead of running expensive queries using Thanos-Query. I was wondering if we can potentially fetch it directly from block storage to be analyzed/mined. Ideally, we should be able to access the data in a format where we can use distributed tools like Apache Spark to analyze it.

I understand the current format in which the data is stored is: https://github.com/prometheus/prometheus/tree/master/tsdb/docs/format

Has anyone able to convert/translate this into a more programmatically importable format? for eg: Parquet, ORC, etc.

Any help and pointers welcome :)

**Comment by bwplotka** [comment]
I am curious as well. Shared on our Thanos slacks as well :+1: @maulikjs can you send same message on prometheus-users mailing list as well? https://groups.google.com/forum/#!forum/prometheus-users :thinking: As it is literally Prometheus format and there are many many Prometheus users on the wild :hugs:

**Comment by ashidhull** [comment]
Can we not hit the TSDB directly? https://events.linuxfoundation.org/wp-content/uploads/2017/12/AIOps-Anomaly-Detection-with-Prometheus-Marcel-Hild-Red-Hat.pdf

**Comment by bwplotka** [comment]
As mentioned on the slack comment: https://cloud-native.slack.com/archives/CK5RSSC10/p1583857282235500 you can definitely work on Prometheus/Thanos APIs but those are designed for real-time experience. For analytics, you might want to process large analytic data for a longer time, but it can be delayed and ran out of band. 

Working directly on TSDB format OR implementing some analytics query API for Thanos/Prometheus (long-running jobs) might be a good idea then :+1: Question is, do users need that or maybe someone tried already! :hugs:

**Comment by bwplotka** [comment]
Let's reopen as it's still valid. We had a similar question here: https://cloud-native.slack.com/archives/CK5RSSC10/p1590621940211100

> Has anyone able to convert/translate this into a more programmatically importable format? for eg: Parquet, ORC, etc

I think the key question here is NOT about how to use TSDB format 
I think the way to go is to agree on some API that will work for mining on TSDB format directly, so we either have some StoreAPI or direct TSDB format adapter to such API.


I don't think the conversion is the way to go, but it is some idea.

Now we are actually slowly looking on our side (Red Hat) as well for some analytic tool, potentially OLAP like open source system that will allow us to produce meaningful, multidimensional reports. Metrics data would be one thing, but actually the requirement is to join data from various data sources, like Segment.io, Prom based Metrics, potentially logs, and others... 

I did not research too deeply yet, but 

Do you have any APIs in mind that would work for this? Google pub sub? Anything on OLAP side? I did not research anything, but we might want to use

**Comment by bwplotka** [comment]
We had a similar question here: https://cloud-native.slack.com/archives/CK5RSSC10/p1590621940211100

> Has anyone able to convert/translate this into a more programmatically importable format? for eg: Parquet, ORC, etc
I think the way to go is to just operate on object storage data on TSDB format. We can totally help in designing some integrations with those



I think the key question here is NOT about how to convert TSDB format, because that's really easy. You just spend 2h to understand TSDB format or StoreAPI and implement a tool/service that will continuously convert things. That's the easy part.

**The key question is... convert to... what?**

There are many systems on the wild and it's also outside of my expertise. However, nowadays we are actually slowly looking on our side as well for some analytic tool, potentially OLAP kind of open source system that will allow us to produce meaningful, multidimensional reports mainly from metrics. It's worth noting that metrics data would be just one data source, but actually the requirement is to join the data from various sources, like segment.io, Prom based Metrics, potentially logs, and others... 

I did not research too deeply yet, but I think the way to go for this issue is to research and find (if exists) such a system that is open source and meets our requirements. Once we agree, as Red Hat we will definitely create (in some other repository) some integration tool that will work smoothly with Thanos. But even if we choose something it does not mean it will meet someones else goal. Today, however, there is no decision on what that target system is. :hugs: 

Does anyone have something that works using open-source system that is willing to share their experience? How you analyze data nowadays? From segment, etc ? I personally have only experience with [Google BigQuery](https://cloud.google.com/bigquery), but I think we might want something for it.

**Comment by bwplotka** [comment]
We had a similar question here: https://cloud-native.slack.com/archives/CK5RSSC10/p1590621940211100

I think the way to go is to just operate on object storage data on TSDB format. We can totally help in designing some integrations with those APIs like you mentioned, but the idea is to allow the community to build a StoreAPI or TSDB Format based adapters for it :hugs: 

> Has anyone able to convert/translate this into a more programmatically importable format? for eg: Parquet, ORC, etc

I think the key question here is NOT about how to convert TSDB format, because that's really easy. You just spend 2h to understand TSDB format or StoreAPI and implement a tool/service that will continuously convert things. That's the easy part.

**The key question is... convert to... what?**

There are many systems in the wild and it's also outside of my expertise. However, nowadays we are actually slowly looking on our side as well for some analytic tool, potentially OLAP kind of open-source system that will allow us to produce meaningful, multidimensional reports mainly from metrics. It's worth noting that metrics data would be just one data source, but actually the requirement is to join the data from various sources, like segment.io, Prom based Metrics, potentially logs, and others... 

Let's start separate issue on finding such a system together, maybe someone has some ideas (: 

This issue is solved as our way to go IMO is that anyone is welcome to build a conversion tool/adapter. We can even offer to start a community project at https://github.com/thanos-community org for this. But there is no clear even API, a format that people are looking for, so not sure what actionable would be here from Thanos project itself :hugs:
