### ISSUE TITLE
Prometheus pod goes to crashloopbackoff with sidecar

### ISSUE THREAD

**Issue by raz08** [thanos-io/thanos#2285]
**What happened**: Deployed prometheus with thanos sidecar, Prometheus pod went crashloopbackoff. I found this issue only once. I tried to reproduce but not helped.

**What you expected to happen**: Prometheus should come up with sidecar

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**: sidecar logs
level=warn ts=2020-03-11T21:59:13.588101757Z caller=sidecar.go:219 msg="heartbeat failed" err="request flags against http://localhost:9090/api/v1/status/config: Get http://localhost:9090/api/v1/status/config: dial tcp 127.0.0.1:9090: connect: connection refused"

**Anything else we need to know**:

**Comment by daixiang0** [comment]
It is related to https://github.com/thanos-io/thanos/blob/master/cmd/thanos/sidecar.go#L236-L251, i guessed it occur when prometheus has long time startup, if so it can be reproduced, in fact it can not.

**Comment by yeya24** [comment]
This crashloopbackoff happens a lot, but I think it is ok because usually it only happens once. When Prometheus is ready, then everything is fine. 
 I think the root cause is that currently in one pod, the initialization order of each container is not predictable. That's not what we can control in Thanos.

**Comment by bwplotka** [comment]
Yes, this is expected really in this format, unless Kubernetes will add sidecar order startup or something.
