### ISSUE TITLE
compact: Add a warning within compact doc for --retention.resolution-raw=xd, will remove raw objects from the object store keeping only xday of data.

### ISSUE THREAD

**Issue by romoy** [thanos-io/thanos#2290]
Thanos version: https://github.com/thanos-io/thanos/releases/tag/v0.11.0-rc.1

**Object Storage Provider**:
s3

**What happened**:
--retention.resolution-raw=xDay, removed all raw data greater than the day from the object store

**What you expected to happen**:
From how I read the doc for retention, there is a feeling that all the raw data would remain except the query results would use the xDay of raw up to the yDay of 5m then the zDay of 1h.

**How to reproduce it (as minimally and precisely as possible)**:
Seed the object store with 60d of data
Add the following config to compact
--retention.resolution-raw=7d
--retention.resolution-5m=14d
--retention.resolution-1h=30d
Deploy compact

**Comment by romoy** [comment]
This could be the same issue as https://github.com/thanos-io/thanos/issues/1674.

**Comment by raffraffraff** [comment]
I don't think that triggering that warning in that situation would get the correct message across. When I was implementing Thanos, I would have shrugged at such a message and thought "yup, that's exactly what I want". The 'brokenness' does not occur when you set some arbitrary _raw_ retention value, the problem occurs when the values for 'raw', '5m' and '1h' _differ_. If 'raw' retention is lower than '5m' or '1h', then short-span graphs will be empty beyond the raw retention point, because the Thanos Querier chooses granularity not based on the age of the data, but on the width of the timespan.

Suggestion: warn if retention values differ between raw, 5m, 1h. The message should be something like this:

> Downsampling is not intended to save on storage space by removing raw data after a short perod. Doing this will break your graphs after the retention period on any short time span. The purpose of downsampling is to reduce the number of data points in graphs that use long time spans (eg: months)

**Comment by Reamer** [comment]
I think the documentation is good. Raw data is not required, if you want to zoom in your data. You can also zoom into a 5m resolution data. 
If your working with Grafana, you should disable "auto-downsampling" in querier and work with different Grafana prometheus datasources. Each prometheus datasource should have an other value in `CustomQueryParameters` for `max_source_resolution`. For `CustomQueryParameters` you need a least grafana 6.5, take a look into this nice feature (https://github.com/grafana/grafana/pull/19121).
Grafana dashboard templates should help you to reach this setting. The time value for a `rate` function should also be variable.

**Comment by belm0** [comment]
@Reamer would you kindly clarify why the Compactor `auto-downsampling` option doesn't work with Grafana?

Does it mean that Grafana is already careful about using the correct step size, and the "step / 5" rule is sufficient?

**Comment by Reamer** [comment]
Hi @belm0 
`auto-downsampling` is an option from the Querier component - [relevant documentation](https://github.com/thanos-io/thanos/blob/master/docs/components/query.md#auto-downsampling).
Grafana is using this component, when you query Prometheus data saved with Thanos.
Grafana also sends a `step` information for good resolution - [Prometheus-Datasource](https://grafana.com/docs/grafana/latest/features/datasources/prometheus/)

If you do not want to save RAW data for months because you only have limited storage space but want to zoom into your data with a resolution of `5m` or `1h`, the calculation `step / 5` with `auto-ownsampling` does not work.

> Is it only about being specific about the resolution you want to query? So I set up several Grafana datasources to the same thanos, each with different max_source_resolution.

Yes, you are correct.

> But dashboards have variable time ranges. So the query author doesn't know if it will be used for 1 day or 1 year...

The time ranges like in `irate` or `rate` should also be variable via Grafana dashboard templating.

**Comment by bwplotka** [comment]
help wanted, very needed (:
