### ISSUE TITLE
Queries don't timeout

### ISSUE THREAD

**Issue by roastiek** [thanos-io/thanos#2314]
**Thanos, Prometheus and Golang version used**:

thanos 0.11.0, go1.13.7
**Object Storage Provider**:
s3 / ceph

**What happened**:
Queries don't timeout after specified `--query.timeout=180s` and keeps running. The metric `prometheus_engine_queries` goes up and and never down until the `query` instance is restarted. Queries come from `rule` and can run for hours instead of seconds.

It happens on all instances of `query` at the same time so its propably related to temporary problems with some stores.

**Anything else we need to know**:
I have rolled back `query` to 0.10.1 and keeped rest of compontest on 0.11.0 and this is working for me for now.

Looking `git log` I have picked and tested these two commits.
2e3ece187f8fe3a356609a3ee3457162ce7f8545 works
c39ddb2559ecaea4bcd754d8456016ed2e96f67e broken

I suspect this commit is the cause a354bfbac862ad6eab5af94d10f597079b6ad175

**Comment by GiedriusS** [comment]
Hi! Sorry for the problems. Can't say anything about this specific problem but I wouldn't be surprised if this is related to https://github.com/thanos-io/thanos/issues/2213. Thanks for dissecting this to almost a specific commit. Could you try reverting that commit on https://github.com/thanos-io/thanos/commit/c39ddb2559ecaea4bcd754d8456016ed2e96f67e and see if it helps?

**Comment by deedrah** [comment]
Yes, I will try that tomorrow.

**Comment by deedrah** [comment]
So I was able only run a354bfbac862ad6eab5af94d10f597079b6ad175 and the problem was present.

I am running v0.11.0 with both a354bfbac862ad6eab5af94d10f597079b6ad175 and c39ddb2559ecaea4bcd754d8456016ed2e96f67e reverted on query now and it is prefectly stable.

**Comment by roastiek** [comment]
I haved missed that number of goroutines goes up too as they got stuck. So I have dumped them with `/debug/pprof/` [goroutine.txt](https://github.com/thanos-io/thanos/files/4426627/goroutine.txt)

**Comment by GiedriusS** [comment]
> I haved missed that number of goroutines goes up too as they got stuck. So I have dumped them with `/debug/pprof/` [goroutine.txt](https://github.com/thanos-io/thanos/files/4426627/goroutine.txt)

I have spent some time on this and it seems like this is some tricky edge-case. All of our tests on slow StoreAPI nodes also pass on the latest master. I have made some adjustments to them in my own branch but couldn't catch anything.

Does it help if you apply the following patch:

```diff
diff --git a/pkg/store/proxy.go b/pkg/store/proxy.go
index 974a2521..bb77bd09 100644
--- a/pkg/store/proxy.go
+++ b/pkg/store/proxy.go
@@ -443,7 +443,7 @@ func startStreamSeriesSet(
 }
 
 func (s *streamSeriesSet) handleErr(err error, done chan struct{}) {
-       defer close(done)
+       close(done)
        s.closeSeries()
 
        if s.partialResponse {
```
?

**Comment by roastiek** [comment]
I think the culprit is this https://github.com/thanos-io/thanos/blob/cc6c5b54baf7ea92edef84da475a1e97ab1d21ec/pkg/store/proxy.go#L437
It does not handle context cancel like in the original version
https://github.com/thanos-io/thanos/blob/f034581bffbb15324a7608236282e035f2c989d2/pkg/store/proxy.go#L413-L418

What is happening is that many proxy are waiting there with responses ready to be merged but some of them are errors. Then the request fails, merge is aborted and request context is canceled with rest of the proxies stucked.

**Comment by roastiek** [comment]
I'm using v0.11.0 with this patch and did not encounter any problems in last two days.
```diff
diff --git a/pkg/store/proxy.go b/pkg/store/proxy.go
index 974a2521..8700e1be 100644
--- a/pkg/store/proxy.go
+++ b/pkg/store/proxy.go
@@ -436,7 +436,14 @@ func startStreamSeriesSet(
 				s.warnCh.send(storepb.NewWarnSeriesResponse(errors.New(w)))
 				continue
 			}
-			s.recvCh <- rr.r.GetSeries()
+
+			select {
+			case s.recvCh <- rr.r.GetSeries():
+				continue
+			case <-ctx.Done():
+				s.handleErr(errors.Wrapf(ctx.Err(), "failed to receive any data from %s", s.name), done)
+				return
+			}
 		}
 	}()
 	return s
```

**Comment by GiedriusS** [comment]
> I'm using v0.11.0 with this patch and did not encounter any problems in the last two days.
> 
> ```diff
> diff --git a/pkg/store/proxy.go b/pkg/store/proxy.go
> index 974a2521..8700e1be 100644
> --- a/pkg/store/proxy.go
> +++ b/pkg/store/proxy.go
> @@ -436,7 +436,14 @@ func startStreamSeriesSet(
>  				s.warnCh.send(storepb.NewWarnSeriesResponse(errors.New(w)))
>  				continue
>  			}
> -			s.recvCh <- rr.r.GetSeries()
> +
> +			select {
> +			case s.recvCh <- rr.r.GetSeries():
> +				continue
> +			case <-ctx.Done():
> +				s.handleErr(errors.Wrapf(ctx.Err(), "failed to receive any data from %s", s.name), done)
> +				return
> +			}
>  		}
>  	}()
>  	return s
> ```

Thank you for your patch! I believe that the problem is a bit more nuanced. I will print out below what I had found out so far. I hope it will be useful. Maybe I am wrong, feel free to disagree.

My "stupid" way of reproducing is by doing this change:

```diff
diff --git a/pkg/store/proxy.go b/pkg/store/proxy.go
index 8440de2f..e801d98b 100644
--- a/pkg/store/proxy.go
+++ b/pkg/store/proxy.go
@@ -430,11 +430,13 @@ func startStreamSeriesSet(
                        }
                        numResponses++
 
-                       if w := rr.r.GetWarning(); w != "" {
-                               s.warnCh.send(storepb.NewWarnSeriesResponse(errors.New(w)))
-                               continue
+                       for i := 0; i < 15; i++ {
+                               if w := rr.r.GetWarning(); w != "" {
+                                       s.warnCh.send(storepb.NewWarnSeriesResponse(errors.New(w)))
+                                       continue
+                               }
+                               s.recvCh <- rr.r.GetSeries()
                        }
-                       s.recvCh <- rr.r.GetSeries()
                }
        }()
        return s
```

I think it reproduces the same issue you are having. At the very least the backtraces are the same.

And running:
```
THANOS_ENABLE_STORE_READ_TIMEOUT_TESTS=1 /usr/bin/go test -v -timeout 60s github.com/thanos-io/thanos/pkg/store -run '^(TestProxyStore_SeriesSlowStores)$'
```

Gives us the same backtrace.

Now, notice that we currently stop merging the series sets as soon as one of them errors out:

https://github.com/thanos-io/thanos/blob/master/pkg/store/storepb/custom.go#L139-L141

Since now not only the series context can exceed its deadline but also there is the `frameTimeoutCtx`, we might abruptly stop merging content from other series sets and those goroutines might be left hanging just like in your case. The `sync.WaitGroup` then never arrives at zero and we get a deadlock.

A stupid way would be to check the context of the error and continue merging if the series context does not exceed its deadline:

```go
	if s.adone && s.bdone {
		return false
	}

	err := s.Err()
	if err != nil {
		if strings.Contains(err.Error(), "failed to receive any data from") {
			return false
		}
	}
```

OTOH the `frameTimeoutCtx.Error()` string would contain the duration itself. It would look like: `failed to receive any data in 4s from ...`. So, this would be a lazy way to detect this and continue on with our work. It is only possible if the `Series` context still exists. This is ensured by the store client i.e. `s.stream` being protected by that context:

```go
		go func() {
			for {
				r, err := s.stream.Recv()
				select {
				case <-done:
					close(rCh)
					return
				case rCh <- &recvResponse{r: r, err: err}:
				}
			}
		}()
```

The tricky part here is that we still want to have these errors, even if one of them start dropping them. So, the alternative to continue merging until both of them error out won't work.

AFAICT the only solution here is to ignore frameTimeoutCtx errors in one way or another. Thoughts?

**Comment by GiedriusS** [comment]
Finally came up with a normal test-case: https://github.com/thanos-io/thanos/pull/2411 :smile_cat:

**Comment by roastiek** [comment]
Nice. I was trying to write up a test case. But somehow I got the fix first.

I will try 0.12.0 day or two after release to confrim that the problem is gone.
