### ISSUE TITLE
query: document / log case of redundant stores

### ISSUE THREAD

**Issue by belm0** [thanos-io/thanos#2436]
**What happened**:
banzaicloud thanos chart has a `replicaCount` parameter for Store, so I assumed that this was a way to distribute Store load and provide redundancy.

The behavior of Query when there are stores with the same label sets and time range isn't documented.

> me: if there are two Store replicas with the same label sets and time range, am I correct that Query will only hit one of them when executing a query? (edited) 
>
> Frederic Branczyk: it will hit both, currently I recommend having only 1 store replica that serves the same data

**What you expected to happen**:

Query behavior when there are redundant stores should be documented, and perhaps Query should issue a warning when it sees redundant stores.

**Comment by GiedriusS** [comment]
I think this concern is understandable. Thanos Query does this already to some degree - the IPs/ports needs to be the same. There's even a metric called `thanos_query_duplicated_store_addresses_total`. However, it doesn't look at the contents of the metrics that StoreAPIs expose. I would imagine that it is infeasible to calculate the hash over all of the metrics content that Thanos Store "sees", for example, because we would have to look not only into indices but also the series data. However, we _could_ add some check and log if the min/max times + exposed label sets of >1 StoreAPIs match up after 10 Info() calls, let's say. I can imagine it helping our users increase the efficacy of their setups.
