### ISSUE TITLE
receive,ruler: Potentially leaking disk from TSDB Mmap-ed chunks.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2677]
Introduced on `master` by:  https://github.com/thanos-io/thanos/pull/2658 (`0.13` is fine)

Tracking ticket on Prometheus https://github.com/prometheus/prometheus/issues/7305

**Comment by bwplotka** [comment]
Affected from https://github.com/thanos-io/thanos/commit/f7802edbf8306c07cc51435425d8f61b7fb94716 commit.

**Comment by codesome** [comment]
Fixed in https://github.com/prometheus/prometheus/pull/7306, I will open a PR for Prometheus upgrade tomorrow. And I think it should go against release branch and even the latest Prometheus upgrade which happened in master should go in 0.13 because the old upgrade does not include fix to the memory leak in isolation which is there in latest upgrade.

**Comment by bwplotka** [comment]
Hmmm, ok.

 Let's do serparate updates for release and master then.

**Comment by bwplotka** [comment]
Let's not put too much on `release-0.13` to reduce risk

**Comment by bwplotka** [comment]
https://github.com/thanos-io/thanos/pull/2697 for isolation fix on 0.13.0
