### ISSUE TITLE
[Feature] sidecar should upload compact black 

### ISSUE THREAD

**Issue by vsxen** [thanos-io/thanos#2886]
Instead of  upload -> download -> compact -> upload again.

**Comment by belm0** [comment]
Thanos uses a different compaction schedule than Prometheus, related to its downsampling sizes.

Usually Prometheus is configured to only hold a few hours of data, and compaction is disabled.  So Prometheus cannot do higher-level compactions since it doesn't have the history.

So thanos-compact needs to do the higher-level compaction anyway, and has to do downsampling and compaction of downsampling blocks.  So it's simpler for thanos to deal exclusively with raw blocks.

**Comment by yeya24** [comment]
Sidecar can already do this. Please see https://github.com/thanos-io/thanos/blob/master/docs/components/sidecar.md#upload-compacted-blocks-experimental

**Comment by vsxen** [comment]
> Sidecar can already do this. Please see https://github.com/thanos-io/thanos/blob/master/docs/components/sidecar.md#upload-compacted-blocks-experimental

I will try it thank you.

**Comment by bwplotka** [comment]
Try to find out the root cause of the problem. We have many ceph users running Thanos just fine. Maybe it's not enough resources on store Gateway side? Maybe it's actually inefficiency on querying both Prom and form Ceph date? Maybe something else?

And what this `the compact is slow` what do you mean? (: 

Pushging compacted blocks actually will make potential compaction slower and more expensive as the vertical compaction has to be made. So currently we don't allow that for long run as usually there is no good reasons for that - the compaction is really similar on Prometheus as in Thanos Compactor - the only  difference is upload / download form /to object storage. Maybe some cache layers or even replicating  to minio would help you.

Closing this issue as it looks stale, but feel to comment and we will reopen (:
