### ISSUE TITLE
Can I save disk space by reducing retention time?

### ISSUE THREAD

**Issue by computerphilosopher** [thanos-io/thanos#2894]
Disk space required to use downsampling is too burdensome.

I'd like to know if I can save disk space by reducing the retention period of raw data.

here is an example.

retention.resolution-raw: 1d
retention.resolution-5m: 5d
retention.resolution-1h: 0

If I set it up as above, will I save disk space by leaving only 1h data after 5 days?

**Comment by soniasingla** [comment]
Hi @computerphilosopher, there is already created [issue](https://github.com/thanos-io/thanos/issues/813) that you might want to check. It is well explained by Bartek 🤗

**Comment by GiedriusS** [comment]
Hi! No, in fact setting it to `0` will make it so that the blocks will be kept around forever. And setting it to some small value does _not_ mean that the downsampled blocks won't be produced. Instead, they will be deleted very quickly. Please take a look at https://thanos.io/components/compact.md/ and https://github.com/thanos-io/thanos/issues/813. Closing as a duplicate
