### ISSUE TITLE
sidecar or receiver mode

### ISSUE THREAD

**Issue by zhenkm0507** [thanos-io/thanos#2896]
I have several prometheus instances in different data centers. These data centers are in different cities.
I want to achieve a global view of data, because my one application's metric data are distributed in several prometheus instances in different cities.

First, I try sidecar modes，but failed. it takes over 5 seconds between querier and sidecar, when the count of time series is more than two thousands.

My thanos version is 0.13.0，prometheus version is 2.10.
the sidecar and prometheus are deployed in one machine, the querier is on another machine in a differenct city.

What's wrong? Help me!

**Comment by kakkoyun** [comment]
@zhenkm0507 Thanks for reaching out. We need more info on this. What is the amount of data? What is your time range query? 

The receiver could help of course, if your latencies caused by your network latencies. And your receivers and queries live closer spatially. 

Also, what do you think about asking this question in our slack channel #thanos in https://slack.cncf.io You would get faster help from the community.
