### ISSUE TITLE
Batch Store API / Query API

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2948]
To brainstorm: Separate to [Analytics API discussions and supported formats](https://github.com/thanos-io/thanos/issues/2682) we might want to make sure Thanos APIs supports long-running jobs and advanced scheduling/prioritization of it: aka Batch APIs.

**There are two main APIs:**

* Query (PromQL eval) and blob return without streaming of results.
* Store API streaming fetching raw samples without any aggregations.

Each of those APIs are commonly configured to have some kind of shorter or longer (but definitive) server side timeouts.

## ACs: 

* User can schedule long running request to fetch large cardinality and time retention. Scheduled computation will batch and scheduled in many steps and use as much time as needed and as many resources as it's allocated for it. The response should be streamed to the user. This can be divided further:
  * **Direct analytic use cases:** User can request `aggregated / computed` using PromQL. The results will be used directly.
  * **Indirect analytic and export use cases:** Users can request raw data in order to use other tools like Spark, Parquet etc. The raw timestamps are preferred (instead of alignment often forced by PromQL) 
* The capability to stream back the progress and show on UI (for Query this means streaming)

## Query API

* Query API is not streaming
* Batching in simple for exists through query-frontend, but:
   * It splits by time without block, limits or actual requests awareness.
    * It  does not persist intermediate results (is it needed?)
* Map Reduce PromQL parallelization is non-existing.
* Raw data fetch through this is hard or even impossible without stable scrape interval known upfront. (maybe this alignment is not a big deal?)

## Store API

* There is no batching existing.
* No PromQL aggregations available. It just fetches raw data.

NOTE: Aggregations can be done via Rules + Backfilling

cc @brancz @pracucci 

BTW @brian-brazil I don't think for this use case we can escape from not designing Query API. For a start, we could do that on Thanos, Cortex. :thinking:

**Comment by brian-brazil** [comment]
Per discussion with @robskillington at PromCon it sounded like no new APIs were required, only building on top of what is already available.

> There is no batching existing.

I believe we were discussing the Prometheus streaming remote read endpoint as the solution here, which basically does what's needed already.

**Comment by bwplotka** [comment]
Yup, however I want to make sure if really no-aggregation / evaluation API is the way to go. 

> I believe we were discussing the Prometheus streaming remote read endpoint as the solution here, which basically does what's needed already.

I think, especially in Thanos world this has to be batched, and while possible to batch those on the client side, no one ever will implement something such complex in an efficient way. We have to support this server side. Plus time-batching is the only possible thing right now, so we might need to think about series dimension split as well.

**Comment by ozanminez** [comment]
I don't know if we will use Apache Arrow or not, but as a candidate, these are my early findings about the project. 

According to Apache Arrow documentation, 
(First three topics below are based on this page. 
There is another extra finding at the end but it is not based on that page.)
https://arrow.apache.org/docs/status.html

I have to mention and clarify this before all topics: Most common data types like float,int,boolean,timestamp,string etc. and lists,structs are available in all almost all languages including Go, C++, Java. But in case of features like Streaming and Parquet file creation there are differences and some missing features between language binding libraries in Apache Arrow project.


1. This is for Remote Streaming use case (sharing data between hosts via grpc):

   There is no Flight gRPC transport feature implementation for GO, 
It is only for C++ and Java 
(It says: Python, R, Ruby and C/GLib libraries follow the C++ Arrow library.)

   In this case maybe we can use C/C++ libraries in Go using something like cgo or c2goasm. But i don't know if our current projects has dependency to any C libraries or it is preffered in common or not. If there is not any other C/C++ dependency currently, it will be another decision to make for adding it to the project.


2. This is for Local Streaming (only in memory, single application in single host) but not for Remote like using host and port and grpc protocol:

   Apache Arrow has libraries for all languages including Go for IPC Format (Arrow stream format + Arrow file format + Record batches)
   IPC Format (aka Arrow Columnar Format) uses Google’s Flatbuffers project. On their Github repo, it says: 
   "FlatBuffers is a cross platform serialization library architected for maximum memory efficiency. It allows you to directly access serialized data without parsing/unpacking it first, while still having great forwards/backwards compatibility."


3. And also this is for the Parquet file creation use case:

   Apache Arrow has only C++ libraries/bindings for Parquet file creation. (And also for Python because it follows C++ libraries.) So there is no native support for reading or writing Parquet files from Arrow Format in Go. It is only possible via embedding C/C++ into Go project.


4. This is an extra finding about Parquet files from the Apache Arrow documentation which is suprising and new for me and it may be useful even without Apache Arrow.

   It is from that page:
   https://arrow.apache.org/docs/python/parquet.html#writing-to-partitioned-datasets

   It says there is a partitioned multiple Parquet files and folders format called "Parquet dataset" which has year, month as nested-folders and files as the day of month.
   There is year and month in this example but it can be used for any partion column. In our case it can be like metric names and labels at the top folders and year and months as sub folders. Probably day is also can be a nested folder so hours or minutes can be the file names. We can discuss the proper structure later.
   They have that Python example built-in function/method called "write_to_dataset" for create Parquet files in that format. (Which partition columns can given as parameter named partition_cols). 
   If this method exists in Python it should exist in C/C++ library/bindings but it seems it doesn't exists in C++ library according to that page: https://arrow.apache.org/docs/cpp/api/formats.html#parquet-writer

**Comment by bwplotka** [comment]
Closing this is fair as we started https://github.com/thanos-community/obslytics that takes remote-read / StoreAPI and produces parquet / other formats (:

**Comment by bwplotka** [comment]
Let's see how that goas!

cc @ozanminez if you want to help us (:
