### ISSUE TITLE
Feature Request: Add GRPC-Web to thanos

### ISSUE THREAD

**Issue by jdfalk** [thanos-io/thanos#3058]
When using an ALB or other Load Balancers / certain istio configs you cannot connect to a thanos instance behind it due to their GRPC issues. I think that could be solved with [grpc-web](https://github.com/improbable-eng/grpc-web). An implementation you should be intimately familiar with considering you (improbable-eng) developed it 😄

**Comment by bwplotka** [comment]
This is something you can totally solve using https://github.com/grpc-ecosystem/grpc-gateway on your side! (: 

grpc-web is for something else - to ensure you can use gRPC inside web browsers :heart:  (: 

Since grpc-gateway is just a sidecar, anyone can totally set this up on their own, but good point, thanks! (: 

(PS: Probably we should focus on fixing gRPC issues on those load balancers as well :scream: )

**Comment by jdfalk** [comment]
Agreed on them fixing their nonsense load balancers, but if you look at Argo-CD they did some great work using grpc-web to allow their [cli tool to access the grpc server behind any load balancer](https://github.com/argoproj/argo-cd/blob/master/pkg/apiclient/grpcproxy.go).  It might be worth looking at implementing the same thing. grpc-gateway creates a rest endpoint but we literally just want to do:
thanos query -> Application Load Balancer -> thanos query

I could be dense but I don't think the grpc-gateway will help us do that unmodified.
