### ISSUE TITLE
QoD handling: Improve Thanos Query (Read) Limits 

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3151]
We are adding new options to add limits per samples in multiple components to avoid OOMs/DDoS/Saturation etc but still, it's far from being perfect and it's hard to calculate what value actually to put when you use X GB of mem and Y amount of CPU.

This issue is to gather ideas and suggestion about what we can do in this space. E.g:

Debuggability: 
* Allowing partial response on limited queries: https://github.com/thanos-io/thanos/issues/3074 (or on timeouts)

Better limits:
* Automatic resources based limits?
* Clear CPU/Mem per X samples number for manual calculations for each component?
* Better docs on what we have so far (connection limit and sample limits)

Related: https://github.com/thanos-io/thanos/issues/2527

Let us know in the comment what else we can improve (:

**Comment by bwplotka** [comment]
Related discussion: https://cloud-native.slack.com/archives/CK5RSSC10/p1599398876160300

**Comment by tdinucci** [comment]
**Problems**
1. It is possible for individual queries to cause components to OOM
2. It is possible for expensive queries to cause a queue of queries to form and then for even cheap queries to timeout.

**Considerations**
These issues may be mitigated by actions such as; reducing timeouts, scaling out queriers, etc - lowering the blast radius of any single "bad" query.  These actions alone however cannot guarantee success, overall system complexity increases (i.e. higher number of processes) and it is also frustrating for users to submit a query only for it to fail due to a timeout.

If we can determine that a query has an excessive cost before executing it then we could reject this query before attempting to execute it.  This should help greatly with the 2 problems mentioned and also allow for a reasonable user experience because they will be informed immediately that their query is unacceptable and they must take action, e.g. reduce the time range.  

**Cost Estimation**
In order to estimate query cost we would need a cached set of statistics to refer to, i.e. cardinality of each label within each block. 

These statistics could be generated as data points are ingested however this would not take into account historical data that was recorded before this feature was added.  Potentially a better alternative is a background job which is capable of calculating these statistics in a batched fashion.

In any case, an estimated cost could be generated by referring to the statistics which are relevant to a query and the time range which the query spans.  

This would likely have to be an optional feature where configuration specifies the maximum estimated query cost a Thanos user is willing to pay.  If they don't specify this then all queries will be attempted.

**Etc**
If it is agreed that this feature has potential then it may be the case that a more natural home for it is Prometheus, allowing both Prom and Thanos to benefit.

**Comment by bwplotka** [comment]
Sorry for lag.

Yes, that's the current direction and high level idea. For each component estimate the cost and allow users to give certain limit of those per tenant.

I would focus on StoreGW and Querier first. I love the idea of statistics driven approach. We can totally do extra calculation, every time we create index-header file from index.  Let's dive into this more. cc @krasi-georgiev who is on it.

**Comment by bwplotka** [comment]
But there might even more easier wins. In Posting Matching we can already tell how much postings it's touching. We can estimate something from that. Of course each posting will not tell you immediately how much series and  chunks (and how much samples within chunk) you will return. This is something we need to figure out.

**Comment by bwplotka** [comment]
In fact this might be something we can build into Prometheus block, thus improving Prometheus limits as wel

**Comment by tdinucci** [comment]
Sounds promising 😀 

Having this kind of thing in Prometheus makes total sense since this is a problem there too.

It seems like you're already on top of this.  I can't firmly commit to anything myself over the next couple of weeks however if you think an external contribution would help speed this along I'd be very happy to discuss.

**Comment by bwplotka** [comment]
I wouldn't say we are on top if, it's one of many things and rather not the highest priority now, so any help is welcome! We are always happy to discuss about external help, freel free to each me on CNCF Slack `@bwplotka` or `#thanos-dev` (:

**Comment by tdinucci** [comment]
Cool.  Let me gather my thoughts on this and I will reach out over the next couple of weeks 👍

**Comment by tdinucci** [comment]
As requested, moving discussion back here so they're easier to follow and there's history.

A summary of my thoughts on this topic are:

* I feel it's important that the statistics that are used estimate query cost are not calculated on demand - this would just end up making the majority of queries (which will be acceptable) quite a bit more expensive.

* If we are to store these statistics somewhere it _feels_ like the right place for them is within Prom blocks.

* Storing these statistics within Prom blocks will however mean that in order to estimate the cost for a query that spans many blocks that many blocks would have to be (partially) read in order to read these statistics.  This will be quite expensive and potentially hurt in terms of pushing valuable data out of caches.

* Storing these statistics outside of the Prom block would mean we'd have to somehow duplicate symbols.  There are different ways this could be tackled but in the end it'll result in even more duplication of symbols than there currently is across normal Prom blocks.

* In the end, I feel in order to do something efficient here (and worthy of including in a product like Prom or Thanos) the index format would have to change.  A dump of some thoughts I've had in this area are: https://docs.google.com/document/d/1B7chNtnDhazPY871g3jBAEKiAYqLEygpCmrnqoHThr0/edit?usp=sharing

Anyway, there's obviously a working group that's currently considering the index format.  This process will likely take quite a long time to complete though and I have a fairly urgent need for this type of functionality.  At the moment I feel my best option is to implement this outside of Prom/Thanos.

**Comment by tdinucci** [comment]
Having said the above - there is a chance that the kind of thing I have in mind could be useful as an **optional add-on** to Prom based systems.  

<img width="480" alt="Screenshot 2020-10-10 at 15 11 51" src="https://user-images.githubusercontent.com/35197667/97010149-f22a1f80-153c-11eb-8cbe-f8d0d14d288a.png">

The Scrape Proxy would intercept all data points and could then sample a certain percentage of these to estimate cardinality - using an algorithm like HyperLogLog.  The Query Proxy could then estimate cost before deciding whether to relay the query to the store.

**Comment by yeya24** [comment]
Might be not related to this issue. I just found this memory tracker which can help track the memory usage in Querier and prevent OOM https://github.com/pingcap/tidb/blob/master/util/memory/tracker.go. Do you think it is something we want to have?

**Comment by ianbillett** [comment]
still valid

**Comment by bwplotka** [comment]
Actually, let's close and add fresh one -- this might be too old.

**Comment by BouchaaraAdil** [comment]
link to fresh one @bwplotka ?
