### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by youjiahe** [thanos-io/thanos#3313]
I had set those parameters large enough,but the logs of the 'thanos query' still print ‘too many open files’

## logs
```txt
level=warn ts=2020-10-14T01:58:16.072899124Z caller=proxy.go:456 err="receive series from Addr: *********:10101 LabelSets: [...] Mint: 1599127332401 Maxt: 1602633600000: rpc error: code = Aborted desc = fetch series for block 01EM6J8169K1AG03FWMRPD8KDK: expanded matching posting: get postings: read postings range: get range reader: Head \"http://**************\": dial tcp **********:80: socket: too many open files" msg="returning partial response"
```

## parameters
```bash
[root@CK-Thanos2-HK ~]# tail -3 /etc/security/limits.conf 
# End of file
* soft nofile 12000000
* hard nofile 12000000
[root@CK-Thanos2-HK ~]# sysctl -p | head -2
fs.file-max = 40960000
fs.nr_open = 20480000
```

**Comment by Dylan-Feith** [comment]
Hello, 

since systemd, you should add the following line in the service section to the unit systemd file : /etc/systemd/system/thanos-query.service

LimitNOFILE=yourvalue

(Do not forget systemctl daemon-reload and restart your service)
You can then get the pid of your process and check for the new value with 

cat /proc/pid/limits

Best regards,
Dylan

**Comment by youjiahe** [comment]
Thanks a lot! Get it

**Comment by youjiahe** [comment]
Thanks a lot! Get it

**Comment by kakkoyun** [comment]
It seems like it is just a question about configuration and it's resolved so closing it.
