### ISSUE TITLE
Compactor: Stream compaction and downsampling from Object Storage

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3389]
It would be amazing to skip disk writes/reads and allow Compactor to be fully streaming from object storage.

In order to do compaction streaming, we need to redesign index format a bit (e.g store postings and series in different files).

This is something being explored during [the Prometheus Storage Working Group](https://docs.google.com/document/d/1HWL-NIfog3_pFxUny0kAHeoxd0grnqhCBcHVPZN4y3Y/edit).

cc @brancz @codesome @pracucci

**Comment by bwplotka** [comment]
Actually, downsampling streaming would be extremely easy (: Help wanted!

**Comment by matthiasr** [comment]
Yes, this is still needed. We run our compactor with a 2TB volume just to prevent it from running out of disk.

**Comment by Biswajitghosh98** [comment]
My understanding of the problem is : 
`cmd/thanos/downsample.go` has the `processDownsampling` function which calls `block.Download`, that downloads the Block directory locally, which is then read by `tsdb.OpenBlock` and then the returned object is passed to `Downsample`. 
We need a helper function, which, instead of downloading, streams blocks one by one from object store to Downsample here 
https://github.com/thanos-io/thanos/blob/master/cmd/thanos/downsample.go#L253-L278
Thoughts ? @bwplotka

**Comment by yashrsharma44** [comment]
> My understanding of the problem is :
cmd/thanos/downsample.go has the processDownsampling function which calls block.Download, that downloads the Block directory locally, which is then read by tsdb.OpenBlock and then the returned object is passed to Downsample.
We need a helper function, which, instead of downloading, streams blocks one by one from object store to Downsample here
https://github.com/thanos-io/thanos/blob/master/cmd/thanos/downsample.go#L253-L278

Correct me if I am wrong, but `block.Download` returns a single directory, which would be used by `tsdb.OpenBlock` to iterate through the contents. I think currently, we could only open tsdb block, and then iterate through the chunks(and further iterate the contents). I am not sure, if tsdb provides an API to iterate through the contents of blocks(or something like `tsdb.OpenChunks` which does not exist) so how would we be able to stream data?

**Comment by Biswajitghosh98** [comment]
> > My understanding of the problem is :
> > cmd/thanos/downsample.go has the processDownsampling function which calls block.Download, that downloads the Block directory locally, which is then read by tsdb.OpenBlock and then the returned object is passed to Downsample.
> > We need a helper function, which, instead of downloading, streams blocks one by one from object store to Downsample here
> > https://github.com/thanos-io/thanos/blob/master/cmd/thanos/downsample.go#L253-L278
> 
> Correct me if I am wrong, but `block.Download` returns a single directory, which would be used by `tsdb.OpenBlock` to iterate through the contents. I think currently, we could only open tsdb block, and then iterate through the chunks(and further iterate the contents). I am not sure, if tsdb provides an API to iterate through the contents of blocks(or something like `tsdb.OpenChunks` which does not exist) so how would we be able to stream data?

Yes, I was a little confused regarding whether we'll read a block, downsample it and delete it later, but that is what is already implemented in the codebase. So the other alternative is to stream chunks and downsample on the way. In the most atomic scale, downsample works on Blocks, so I guess we'd need some more discussion before figuring out an approach, because even if we are able to stream chunks, we'll have to change the code for downsample.

**Comment by bwplotka** [comment]
We already stream chunks and do index lookup in streamed way in `pkg/store/bucket.go` (see `func Series(..`) so we can use that as inspiration for reads.

**Comment by bwplotka** [comment]
Simplest solution would be to stream chunk files as blobs.
