### ISSUE TITLE
receive: Load distribution in Thanos Receivers are not evenly distributed

### ISSUE THREAD

**Issue by heartTorres** [thanos-io/thanos#3488]
**Thanos, Prometheus and Golang version used**:
Thanos v15.0

**Object Storage Provider**:
S3
**What happened**:
I have installed - 3 Thanos Receivers, 1 compactor, 1 store, 2 querier. 
1 pod is installed on each 1 node server.
When I re-installed the Thanos Receivers, 1 pod consumes 2x the memory of the other 2 pods. The problem with this is that, since these 3 pods of Thanos Receivers are part of a single hashring, the 3rd pod (thanos-receive-2) gets oomkilled immediately when the other 2 pods still have enough resource space and no metrics are being shown in thanos query.

Note: I did re-install many times, but the behavior is still the same, the 3rd pod still consumes twice the memory than the other 2 pods. I did check the pod itself and there is no other app running on that pod and there is no error in the logs.

<img width="377" alt="Screen Shot 2020-11-23 at 3 04 08 PM" src="https://user-images.githubusercontent.com/65100615/99936050-25aad480-2d9d-11eb-905c-dc0876589204.png">

**What you expected to happen**:
The load/memory should be atleast (close) distributed evenly.

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by kakkoyun** [comment]
Could you please share your Thanos Receive configuration and hashring file?

**Comment by heartTorres** [comment]
Hi @kakkoyun, below are my yaml configs.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-receive
  labels:
    app.kubernetes.io/name: thanos-receive
  namespace: thanos
data:
  hashrings.json: |
    [
      {
        "hashring": "soft-tenants",
        "endpoints": [
          "thanos-receive-0.thanos-receive.thanos.svc.cluster.local:10901",
          "thanos-receive-1.thanos-receive.thanos.svc.cluster.local:10901",
          "thanos-receive-2.thanos-receive.thanos.svc.cluster.local:10901"
          ]
      }
    ]
```
We have dedicated 5 nodes allotted only for Receivers.
Receivers:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: thanos-receive
  name: thanos-receive
  namespace: thanos
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-receive
  serviceName: thanos-receive
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos-receive
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: namespace
                operator: In
                values:
                - thanos
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - thanos-receive
            topologyKey: kubernetes.io/hostname
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - thanos-store
            topologyKey: kubernetes.io/hostname
      tolerations:
      - key: namespace
        operator: Equal
        value: thanos
      containers:
      - args:
        - receive
        - --log.level=error
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --remote-write.address=0.0.0.0:19291
        - --receive.replication-factor=1
        - --objstore.config=$(OBJSTORE_CONFIG)
        - --tsdb.path=/var/thanos/receive
        - --tsdb.retention=3h
        - --label=receive_replica="$(NAME)"
        - --label=receive="true"
        - --receive.hashrings-file=/etc/thanos/hashrings.json
        - --receive.local-endpoint=$(NAME).thanos-receive.thanos.svc.cluster.local:10901

**Comment by kakkoyun** [comment]
Hey @squat, do you have ideas about this? I'd appreciate some pointers?

**Comment by squat** [comment]
> Note: I did re-install many times, but the behavior is still the same, the 3rd pod still consumes twice the memory than the other 2 pods. I did check the pod itself and there is no other app running on that pod and there is no error in the logs

This is actually good and expected behavior. The same time series should always hash to the same node in a hashring of a given size. This means that for a given set of time series, a hashring should always expect roughly the same load distribution.

The fact that one replica sees consistently higher load than the others is most likely due to some inherent lumpiness in the time series being sent. Thanos decides which replica should ingest data by hashing the name and label-value pairs of a time series and picking a corresponding replica from the ring to handle this hash. It seems that the data being sent simply has more time series that hah to one replica. There is no guarantee that data will be distributed uniformly across replicas, however, for a good hash function, the greater the number of time series and the more random the names and labels of those time series, statistically, we should coverage towards a uniform distribution. 

Unfortunately I don't think there is actually a bug here :/ take for example the case where a Prometheus server only produces a single time series and remote writes a million samples/second. We would rightfully expect super high load on a single hashring replica. This is essentially and extreme version of the case we see here.

One thing I could imagine would be to submit a feature proposal to improve the randomness of replica selection and thus drive load distribution towards uniformity even in the degenerate single-time-series case by adding a random value to the hash that changes for every request. It would be important that replicas forward this metadata along with the request so that once it is set, the value is fixed and replicas can agree on who should ultimately ingest a sample. WDYT? This would help solve load distribution for lumpy data.

**Comment by kakkoyun** [comment]
Thanks, @squat taking the time write such a comprehensive comment. I'm thinking right now to convert this to a discussion to guide users who have similar questions. WDYT?

Further more, I liked the proposal we can create an issue for it if it's a needed feature. WDYT @heartTorres?

**Comment by squat** [comment]
yes I think any guide for users would be super helpful :+1: 

I'll go ahead and submit an issue for the feature :rocket:
