### ISSUE TITLE
objstore: Millions of transactions per hour

### ISSUE THREAD

**Issue by p4eb** [thanos-io/thanos#3712]
Hi,

we're using Thanos 0.17.2 (store and comapct)
We see a lot of transactions (GETs and HEADs) hitting on our S3-Storage (Cloudian). 

60' stats
User | Upload | Download | Transactions | GETs | PUTs | HEADs | DELETEs | Total Byte Count | Total Object Count
p-thanos | 2.36 GB | 725.72 MB | **2,946,953** | 989,672 | 9 | 1,957,221 | 0 | 54.37 TB | 201,366

According to the documentation you are using the minio-client-library to connect to the S3 backend. Could you please explain if this works as expected with the default settings or if we have to do some finetuning to decrease the amount of transactions.

Regards,
Andy

**Comment by johannesfrey** [comment]
Hi,

  we are in a similar situation like you (we are also using Cloudian S3). Furthermore, we are being rate-limited by our provider because of too many requests.

  Because of that I started experimenting with some flags/settings in order to reduce parallel request bursts. You can see the commits in following [fork](https://github.com/c445/thanos/commits/prevent-rate-limiting). The changes are pretty "hacky" at the moment, I even went this far to [sleep between requests](https://github.com/c445/thanos/commit/2f754474b69980185d700722f87c8f5cbef4c360), which is surely not a desirable thing to do for most users :slightly_smiling_face:.
  The biggest "challenge" that we had was the initial sync that is done by thanos store (even with memcached). We did deploy multiple replicas of thanos store simultaneously to multiple data centers (~108 instances in total). Each of those instances uses 32 go routines to fetch meta data from S3, which makes it ~3450 parallel requests. So you can imagine that the rate limit kicks in pretty quickly when you e.g. change the image tag or k8s manifest, which forces a restart of all Pods, which in turn triggers an initial sync of meta data again :slightly_smiling_face:.

  The thing that helped us the most was simply [increasing the number of retries](https://github.com/c445/thanos/commit/4487a618f3fe40b083fc2608b79fde56d345710c) of the underlying minio client. This forces the underlying minio client to retry more often after receiving a status code 503 ("SlowDown"). Normally this error would transform into an retriable error in thanos, which would lead to a retry not before the given wait interval, which might be undesirable when this is set pretty high (e.g. 24h).

  Of course, if folks are interested in this I would love to discuss/clean up/contribute our adjustments :).
  
  <sub>Johannes Frey [johannes.frey@daimler.com](mailto:johannes.frey@daimler.com) Daimler TSS GmbH ([Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md))</sub>

**Comment by kakkoyun** [comment]
Hey @johannesfrey, do you have an issue for it? We can evaluate our options and discuss details on an issue or on a design document.

**Comment by johannesfrey** [comment]
Hi @kakkoyun, thanks for your reply. I further experimented with changes and just created https://github.com/thanos-io/thanos/pull/3788. If that's ok, could we also discuss details on the PR. If not I could, of course, also open an issue.

**Comment by kakkoyun** [comment]
@johannesfrey Amazing, thanks! The PR sounds good to me.
