### ISSUE TITLE
Compact all available plans for a single group concurrently

### ISSUE THREAD

**Issue by andrejbranch** [thanos-io/thanos#3806]
### Is your proposal related to a problem?

We are trying to scale the cortex compactor and we have a really large tenant that continues to grow. One problem I noticed is if the compactor fails for some reason and falls way behind it will still only compact 1 set of overlapping blocks at a time instead of concurrently compacting all known overlapping blocks.

### Describe the solution you'd like

 It would help the compactor keep up if we had a way to concurrently compact all available plans for a single group. This would also help when vertical compaction takes a similar amount of time as a blocks time range, as when a new set of overlapping blocks is uploaded the compactor can start another compaction even though one for the same group is already running.

My proposed solution is to move the planning side of the code out of the compaction side and instead have the grouper return a group for every plan available.

### Describe alternatives you've considered

An alternative I considered was changing the planner so that it returns a list of plans and have a new concurrency in the compact code but this is messier and changes the Planner interface.

**Comment by andrejbranch** [comment]
PR for proposed changes https://github.com/thanos-io/thanos/pull/3807

**Comment by dswarbrick** [comment]
This topic interests me, as I've often watched a thanos compactor plod its way through catching up on compactions / downsampling, and wondered why it seems to do a lot of unnecessary work.

For example, assume that the compactor has fallen behind, and you have five 8h blocks, and four (or more) 2h blocks. Theoretically, the compactor could download all those blocks and spit out a 2d block directly. But instead, I've seen it download the four 2h blocks, compact them into an 8h block, and upload it. The work directory is wiped, needlessly throwing away the just-processed 8h block that it's going to need for the next step. _Then_ it downloads the six 8h blocks and compacts them.

The downsampling is another area where the compactor seems to be a traffic generator for the S3 provider. It appears to download the raw block, downsample it to 5m resolution and upload it. A little bit later, it re-downloads the 5m resolution block, downsamples it to 1h resolution, and uploads that. Wouldn't it make more sense to write out the 5m and 1h resolution blocks _concurrently_ so as to save some S3 traffic, and also a save a lot of read IO?

I hope this behaviour isn't simply due to me configuring it wrong.

**Comment by bwplotka** [comment]
@dswarbrick Yes, that's the naive planning Prometheus had, which we inherited. You are welcome to help to find something more scalable! Worked well so far thanks to being... simple! 🙃 

The issue @andrejbranch mentioned might be different and we seen that too - it's very naive for overlaps too. Let's fix both!

Looking on your Pr @andrejbranch thanks for this work 💪🏽
