### ISSUE TITLE
Implement target metadata API

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#3870]
As metric metadata API was merged https://github.com/thanos-io/thanos/pull/3686, it would be good to also support the Prometheus target metadata API (https://prometheus.io/docs/prometheus/latest/querying/api/#querying-target-metadata).

As the API response format is very similar to the previous metric metadata API, it would be not so difficult to support it. We can reuse the existing proto file as well.

**Comment by crsandeep** [comment]
@yeya24 I'd love to take up this issue

**Comment by yeya24** [comment]
Feel free to take it!

**Comment by PhilipGough** [comment]
@crsandeep I will take a go at this unless you are still working on it in the background?

**Comment by crsandeep** [comment]
Apologies, I couldn't get to this.
@PhilipGough please feel free to pick this up

**Comment by ianbillett** [comment]
Chatted with @PhilipGough about this ticket earlier, we were a little confused so just wanted to be more explicit about what we expect the output of a call to Query's `/api/v1/targets/metadata` would be.

Say we had a Querier configured to communicate with two sidecars `StoreAPIs` with two Prometheus instances. Calling `/api/v1/targets/metadata` on each Prometheus returns the following:
```
{
  "status": "success",
  "data": [
    {
      "target": {
        "instance": "localhost:9090",
        "job": "myself"
      },
      "metric": "prometheus_tsdb_out_of_bound_samples_total",
      "type": "counter",
      "help": "Total number of out of bound samples ingestion failed attempts.",
      "unit": ""
    }
  ]
}
```

We assume that the expected output of calling Query's `/api/v1/targets/metadata` would be the same as the above (i.e. one entry per (Target, Metric) tuple, rather than one entry per (Store, Target, Metric) tuple). 

This behaviour would be consistent with the handling of metadata in the [TestMetadataAPI_Fanout](https://github.com/thanos-io/thanos/blob/7bfccf4ea21dcd3e1fd6e95f6caf4de15b11c3e0/test/e2e/metadata_api_test.go#L80) integration test.

Is that in-line with what you were thinking @yeya24 ?

**Comment by majorpeti007** [comment]
I was looking into using the `/api/v1/targets/metadata` endpoint on Thanos Query, and I would have expected the output to be one entry per (Target, Metric) tuple, the same as on Prometheus.

**Comment by gillg** [comment]
Any news around that ? @PhilipGough @ianbillett I saw your closed PRs... :/ Maybe we should reopen they ?

**Comment by PhilipGough** [comment]
@gillg - hey, yes they went stale - I think https://github.com/thanos-io/thanos/pull/4449 can be re-opened and reviewed and I am happy to get back to it if the maintainers find the time.
