### ISSUE TITLE
Support finding peers using AWS API

### ISSUE THREAD

**Issue by wjam** [thanos-io/thanos#395]
One method of running Prometheus is outside of Kubernetes, to avoid the situation where the platform is responsible for ensuring itself is functioning correctly.

To make it easier to run in these situations when running in AWS, Thanos should support discovering the peers in the cluster by searching with the EC2 API for a configurable tag key/value.

**Comment by Bplotka** [comment]
Thanks for your time here! (and for your other PRs!) but we would like to keep number of extension points to a minimum and add dependences were absolutely needed.

Basically, we don't want to have huge dependencies on external packages and we also want to limit the code that for things that not necessarily required. This is because we want to focus our workforce (and contributions) on to what matters in Thanos the most: Global view, deduplication, and unlimited retention capabilities. Imagine this: If we accept EC2 native support, someone will want to add GCE, Azure etc etc

TBH we would love to avoid packages like Prometheus service discovery that pulls multiple huge dependencies and causes Prometheus community to invest lots of precious time to make it stable and up to date. Despite the invested time, I believe that still plenty of users complain about the lack of support for some not popular providers etc..

However, I would love to unblock you on this in the same way, so there are other options than native EC2 SD support, like:
- You can run some external discovery that will put your Thanos components into some DNS entry.
- We can consider a single extension to DNS discovery, similar to [`File SD`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#<file_sd_config>) that will get peers from file that is reloaded in runtime. In this case you can write whatever sidecar you need to get job done. Potentially someone can build appropriate sidecar in a separate repository that supports EC2 discovery, so it is ready for reuse by all users. (: 

I know all other options require some additional work, sorry for that ): But we really want to limit the scope of Thanos to only what is necessary, otherwise we will invest time on maintaining things that are less necessary and not having time for the features or fixes that are must-have.
