### ISSUE TITLE
Unknown long flag '--request.logging-config-file'

### ISSUE THREAD

**Issue by itatabitovski** [thanos-io/thanos#3981]
**Thanos, Prometheus and Golang version used**:
1. thanos-0.19.0-rc.2.darwin-amd64
```
❯ ./thanos-0.19.0-rc.2.darwin-amd64/thanos --version
thanos, version 0.19.0-rc.2 (branch: HEAD, revision: 5620c0955104526dd9cfc7aa4481bfda9030e66c)
  build user:       root@40797d282866
  build date:       20210324-19:00:08
  go version:       go1.15.10
  platform:         darwin/amd64
```

**Object Storage Provider**:
n/a

**What happened**:
```
❯ ./thanos-0.19.0-rc.2.darwin-amd64/thanos query-frontend --http-address="0.0.0.0:10922" --query-frontend.downstream-url=http://localhost:10912 --request.logging-config-file=./logging.yml
error parsing commandline arguments: [./thanos-0.19.0-rc.2.darwin-amd64/thanos query-frontend --http-address=0.0.0.0:10922 --query-frontend.downstream-url=http://localhost:10912 --request.logging-config-file=./logging.yml]: unknown long flag '--request.logging-config-file'
thanos: error: unknown long flag '--request.logging-config-file'
```

I tried to use flag `--request.logging-config-file=` documented [here](https://github.com/thanos-io/thanos/blob/main/docs/components/query-frontend.md) but got error `unknown long flag '--request.logging-config-file'`

**What you expected to happen**:
I expected thanos to start and use the request.logging-config from the file.

**How to reproduce it (as minimally and precisely as possible)**:
Run:
```
❯ ./thanos-0.19.0-rc.2.darwin-amd64/thanos query-frontend --http-address="0.0.0.0:10922" --query-frontend.downstream-url=http://localhost:10912 --request.logging-config-file=./logging.yml
```
**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by wiardvanrij** [comment]
This feature is indeed in the main branch but was not in the cut for the release candidate because that was created at roughly the same time. rc.0 is from 24days ago. The PR for this feature: https://github.com/thanos-io/thanos/pull/3862 was merged 22 days ago. I do understand your point though! 

I would recommend using the docs that are inherent to the version you are using. You can use the docs from this tree: https://github.com/thanos-io/thanos/tree/v0.19.0-rc.2 which should 100% reflect the release.

**Comment by GiedriusS** [comment]
Closing this as it's a non-issue. Let us know if you still have any problems
