### ISSUE TITLE
Query: allow setting min & max time

### ISSUE THREAD

**Issue by wiardvanrij** [thanos-io/thanos#4027]
- The query component implements the store API. 
- StoreAPI components can be chained.
- The sidecar has a -min time
- The store has a -min & max time
- The query has no time

# This is a basic example;

![example-1](https://user-images.githubusercontent.com/5786097/113770397-5ecb5c00-9722-11eb-89c0-ed8982398fae.png)

If we want to limit requests to the sidecar and use the store component, we simply lower the retention of Prometheus with `-storage.tsdb.max-block-duration=2h` (although I prefer to set this to 6-8 hours so we have extra time to fix issues).

# A more complex example

![example2](https://user-images.githubusercontent.com/5786097/113771496-b918ec80-9723-11eb-8303-89eed8b9ebc1.png)

What I want to achieve is to limit the requests to a certain 'stack' and force those requests to our store nodes rather than to the sidecar/Prometheus. 
I think this can be achieved to advertise a min/max time on the query component that will be used by other components. It would look something like this:

![example-3](https://user-images.githubusercontent.com/5786097/113772263-bff42f00-9724-11eb-9d6e-b74c1e9d1c1c.png)

# Use-case
Chicken & egg problem. Our observability stack runs on a cluster. In case our observability stack is having issues or is down, we need to have insights. Therefore having access to Prometheus data is vital. This is still possible by having a higher retention. Yet this also means that long-term queries will get passed onto that setup, while it could be fetched from our stores (which I prefer). 

# Other solution
So to continue, it's about preferences. Multiple components can serve my request, but I prefer they shouldn't via certain 'paths' in the chain. If it was possible to add weight/preferences, then I believe this can also be resolved. For example add preference that queries are done on store components rather than the sidecar/Prometheus. 

_Last note;_
It could be that I'm overthinking this, so I'm also open for any other thoughts :D

**Comment by bwplotka** [comment]
Wow, thanks for this write-down. I wonder if you can highlight the solution that you proposing and maybe clearer enumeration of alternatives. 

We can add simply -min-time and -max-time flags to Querier (like we have in Store GW), and thanks for brining the real life example. It makes sense to me +1

**Comment by GiedriusS** [comment]
Thanks for the nice graphics! What did you use to make them? Unfortunately, it would probably be only possible to implement changing the _min_ time *right now* without bigger changes in how we handle the min/max times in Thanos Query. This is because Sidecars always set the _max_ time to infinity so that they would always be considered when executing a query: https://github.com/thanos-io/thanos/blob/e7fadaf0a0ff34976f4f51301c35a9fa9069297b/cmd/thanos/sidecar.go#L299. In the future we could change this so that the model would be more flexible but I think that warrants a whole new issue and maybe even a design doc :P

**Comment by wiardvanrij** [comment]
> What did you use to make them?  

https://excalidraw.com/ - Can definitely recommend this. I found out via Alex Jones btw :p 


> because Sidecars always set the max time to infinity

Which is not needed to change if we use (or abuse, however you want to see it) the query component as a proxy. 
The point is to have some sort of 'middleware' that can affect min/max times, just by sitting in the middle of it. 

It's my last graph that shows a chained query component. The query component has a `StoreStatus` which then would be overwritten with our query min/max settings.

It might sound a bit dodgy at first but I think it can be a fairly rich feature because it allows you to maintain a high time range on whatever component you want. Yet you can limit and direct queries from and too specific points.

Let's say I have a store. Which has an infinity time-range. I could add 1 query that honours that time-range for 'advanced' users (or whatever the case is). Next I could add an extra query component with a max of 30days. It just overrides ALL the store components with it's fixed min/max times.
Now I have two datasources with different time-ranges, yet still one 'source of truth', all my data, long retention if needed.

**Comment by onprem** [comment]
> Let's say I have a store. Which has an infinity time-range. I could add 1 query that honours that time-range for 'advanced' users (or whatever the case is). Next I could add an extra query component with a max of 30days. It just overrides ALL the store components with it's fixed min/max times.
Now I have two datasources with different time-ranges, yet still one 'source of truth', all my data, long retention if needed.

This sounds like a good feature to have but I think reusing time ranges for doing this might not be a good idea.
1. To me it looks like it's very easy to forgot about these flags on Querier. So scenarios where you increased the retention in Compactor but you still can't see that data in Grafana becomes harder to debug.
2. As far as I remember, I don't think this is how the min-max time ranges work. Let's say we have a Store API with `minTime: now` and `maxTime: -30days`, If I did a query that is even partially overlapping (for ex. -7 days to -90 days) the querier will query that store, because we can get some data from there. So, by just setting maxTime to -30 days we cannot guarantee that this querier will not return data older than 30 days. I can be wrong here though because I haven't actually checked if this is how Querier works.

However, I think advertising min and max time from Querier is a very good idea (if we don't do that already) and if possible it should be calculated implicitly rather than asking from user explicitly. `minTime` can be the minimum of `minTime` of all stores connected to that particular Querier and similarly, `maxTime` can be the maximum of `maxTime` of all stores.

**Comment by wiardvanrij** [comment]
Needs more input

**Comment by wiardvanrij** [comment]
Needs more input
