### ISSUE TITLE
How to send metrics data from thanos to remote object storage for a fix period,such as every 30 seconds?

### ISSUE THREAD

**Issue by btdan** [thanos-io/thanos#4236]
Hi, I want to know is there a method to set the time to send metric data from thanos to remote object storage? 
For example, every 30 seconds I want to send new metric data from thanos to remote object storage.
Thanks very much.

**Comment by thejosephstevens** [comment]
I have a use case for this:

We run k8s clusters that regularly scale between 2 and 30+ nodes, resulting in issues with maintaining a persistent disk for prometheus WAL (in clouds where disks are zonal we can't guarantee we have a node in the same zone as the disk). What we've observed is that when prometheus pods are replaced, they may come back immediately, but if both pods are replaced in less than 2 hours, data is lost due to loss of the WAL. Would it be possible to solve this with a sidecar config or would this require shifting to a remote-write setup?

**Comment by yeya24** [comment]
A push model seems better in your use case.

**Comment by thejosephstevens** [comment]
For anyone who comes across this in future, we moved to a push-based model with cortex which worked much better for our constraints. I would not recommend using thanos to persist metrics in-cluster if you don't have the flexibility to use a persistent disk for the WAL.
