### ISSUE TITLE
Thanos UI autocomplete slow/ freezes browser

### ISSUE THREAD

**Issue by shoopdedoop** [thanos-io/thanos#4500]
**Thanos, Prometheus and Golang version used**:
thanos, version 0.20.1 (branch: HEAD, revision: 10023e4882414baa56a8955057f2678f1e724e8c)
  build user:       circleci@22b1af3c9a07
  build date:       20210430-12:46:55
  go version:       go1.16.3
  platform:         linux/amd64

**Object Storage Provider**:
S3

**What happened**:
Thanos UI autocomplete is very slow.  We are using the Thanos frontend query with the following boxes check under the graph Tab.

Enable autocomplete
Use experimental editor.

When typing in characters the browsers freezes and consumes 100% CPU for about 16 seconds before finally rending the autocomplete data.  We have tried several different browsers all with the same results.  We ran a trace with chrome and we see the following.

On every refresh we see ~8MB of data requested for labels.

api/v1/label/__name__/values

Once the labels are downloaded rendering client side scripting is taking the majority of the time/ cpu, see attached screen shot.
![image](https://user-images.githubusercontent.com/6558065/127510870-f4244ad4-fad8-4550-9c36-a4b78d689468.png)

**What you expected to happen**:

We wouldn't expect autocomplete to be so CPU intensive and freeze the browser

**How to reproduce it (as minimally and precisely as possible)**:
It's easily reproducible.  Gather enough label data.  Use autocomplete within the Thanos UI.

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by Nexucis** [comment]
Hey,

I tried to reproduce on my side, but so far didn't have the issue you are raising and I tried with a huge query too.

* Could you try to upgrade Thanos to the last version ?
* You have perhaps an extension that is causing this effect. Is it feasible to try with an empty and clean browser ?

thanks for your help :)

**Comment by shoopdedoop** [comment]
I upgraded to v0.22.0 and tried fresh browsers.  Firefox, Safari, and Chrome.  Safari does seem a bit snappier but its still slow.

Here is the value capture from Firefox.

![image](https://user-images.githubusercontent.com/6558065/129775181-8ad2968e-128a-47d2-af62-6d839d658bf4.png)

After the values are downloaded the rest of the time is CPU intensive (in each browser), rendering the autocomplete.

**Comment by Nexucis** [comment]
I look a bit closer about what you explained and I compared to what I have.

On my side, the biggest query I can run is when starting to write `{__name__=''}`. 

In that case, we are downloading 279 kB of data which already corresponds to million of metrics name.

In your case, you are downloading ~ 6 MB of data that is corresponding to a label value for the label name `name`. I believe it's matching around hundred million of data.
I will suggest you perhaps to take a time to rethink about the cardinality of your metrics / label you are currently storing.

I'm afraid this is an issue hard to solve or almost impossible as every single item downloaded needs to be processed and known to be able to be autocompleted.
From my point of view, you are just pushing the model to it's extremity and it's quite normal it doesn't work really well.

I know this is not a nice answer, but I believe the issue is more solvable on your side than on our side. And it's not a particular issue on Thanos side side it's totally relative to the lib Thanos is using for autocompleting data. Lib shared by Prometheus and any server supporting PromQL.
