### ISSUE TITLE
Docs: Checking links makes `check-docs` target brittle

### ISSUE THREAD

**Issue by matej-g** [thanos-io/thanos#4732]
Despite the measures to ignore some problematic links via [config](https://github.com/thanos-io/thanos/blob/main/.mdox.validate.yaml#L1), I'm still seeing quite a few failures (e.g. the latest here https://github.com/thanos-io/thanos/pull/4726/checks?check_run_id=3790681280).

I'm wondering how reasonable it is to check availability of all links the different links from documentation, since these are various external resource and even if just one of them cannot be momentarily reached, the tests are failing. This increases the potential for test failures significantly.

**Comment by saswatamcode** [comment]
Yes. This is problematic, especially due to 0 status code errors like this. [Retries](https://github.com/bwplotka/mdox/pull/78) for this were added to mdox but it still fails in some cases.

Currently, mdox checks all links (except config ones) on each PR and push to main. For this purpose, we're planning to add [persistent caching to mdox using SQLite](https://github.com/bwplotka/mdox/pull/54)! So once checked, the links would be cached in [GitHub Actions](https://github.com/actions/cache) and would only be checked again after a specific time period (for eg, ~5d). This should reduce such failures and save time & resources. 🙂

**Comment by matej-g** [comment]
Awesome! Sounds like a cool solution :+1:

**Comment by bwplotka** [comment]
👍🏽

**Comment by matej-g** [comment]
I think this is still needed, did you get a chance to take a look @saswatamcode? Any way I could support you?

**Comment by saswatamcode** [comment]
Yes, the cache [PR](https://github.com/bwplotka/mdox/pull/54) still needs to be reviewed once, so if you can find the time to do so, that'd be great! It can then be merged when @bwplotka is back! 🙂

**Comment by matej-g** [comment]
Still relevant! I pinged @bwplotka to merge the upstream PR, after that nothing should be blocking us here :godmode:

**Comment by matej-g** [comment]
The upstream feature has been merged :tada: and @douglascamata graciously agreed to bring the new mdox release over to Thanos, which should resolve this :muscle:

**Comment by douglascamata** [comment]
Draft PR: #5500

**Comment by matej-g** [comment]
Nice job @douglascamata :100:
