### ISSUE TITLE
Usage service mesh on running thanos

### ISSUE THREAD

**Issue by GounGG** [thanos-io/thanos#4760]
**Version:**
kubernetes: 1.18
thanos: 0.21.1
image: docker.io/bitnami/thanos:0.21.1-scratch-r0

network module：route

**model：**
receive，remote write

**deploy:**
https://artifacthub.io/packages/helm/bitnami/thanos

Why do you do this？
convenient to observe the traffic information and the success rate of writing

**describe：**
The deployment is normal, and through the UI interface, it is found that the nodes are also healthy，But prometheus cannot write normally, and the error message is as follows。

prometheus：
```bash
level=error ts=2021-10-09T08:30:00.630Z caller=queue_manager.go:716 component=remote queue=0:http://xx.xx.xx.xx:xx/api/v1/receive msg="non-recoverable error" count=100 err="server returned HTTP status 409 Conflict: forwarding request to endpoint thanos-receive-3.thanos-receive-headless.thanos-server.svc.cluster.local:10901: rpc error: code = AlreadyExists desc = storelocally for endpoint thanos-receive-3.thanos-receive-headless.thanos-server.svc.cluster.local:10901:"
```

linkerd-proxy:
```bash
[  4595.798425s]  WARN ThreadId(01) server{orig_dst=10.200.64.132:10901}: linkerd_app_core::errors: Failed to proxy request: HTTP Server service in fail-fast client.addr=10.200.64.130:35984
[  4602.846203s]  INFO ThreadId(01) linkerd_app_core::serve: Connection closed error=TLS detection timed out
[  4646.533809s]  INFO ThreadId(01) linkerd_app_core::serve: Connection closed error=connection closed before message completed
```

thanos:
```bash
level=error ts=2021-10-09T08:52:57.046485989Z caller=handler.go:352 component=receive component=receive-handler err="context deadline exceeded" msg="internal server error"
```

**Comment by phillebaba** [comment]
I am seeing similar issues but without a service mesh. My best guess is that it is related to the forwarding timeout.

So the error originates from the receiver handler. The reason the error is so generic is because it is a context deadline error.
https://github.com/thanos-io/thanos/blob/fdfc0776d0c3544a29e1bad5cc49ef971c5b73ef/pkg/receive/handler.go#L365-L367

If you follow the `handleRequest` function call and follow along you end up in the `fanoutForward` function.
https://github.com/thanos-io/thanos/blob/fdfc0776d0c3544a29e1bad5cc49ef971c5b73ef/pkg/receive/handler.go#L426

Here is does a couple of things, one is that it sets up a timeout context using the value of the hidden flag `receive-forward-timeout` as the timeout.
https://github.com/thanos-io/thanos/blob/fdfc0776d0c3544a29e1bad5cc49ef971c5b73ef/pkg/receive/handler.go#L429

I am basically only seing this for metrics series that are very large. My guess is that I am seeing some networking issues when these metrics are forwarded to the other receivers that is causing the issues. One solution would be to figure out why the forwarding is taking so long. The other may be to just increase the forward timeout.
