### ISSUE TITLE
I would propose a dedicated mailinglist specifically for releasing security advisories.

### ISSUE THREAD

**Issue by nfoonf** [thanos-io/thanos#4915]
Security Advisory mailiinglists are industry standard for publishing vital update notifications to users of software products.
There are established processes around security advisories, like automated opening of Tickets upon receiving an advisory which help users to react quickly and fix vulnerabilities before they can be exploited.

A dedicated Mailinglist that only delivers official security advisories would ease the load of users as it is easily integratable into existing processes and compliance guidelines.

I see not really an alternative here, because all alternatives would either require to periodically check sources on the users side or would be difficult to integrate into existing processes.  A mailinglist would allow, after a manual subscribe, to automatically raise issues in a bugtracking system.

Kind regards,
Michael Gröning

**Comment by wiardvanrij** [comment]
I would say it makes sense. Though making the mailinglist is fairly straightforward, I think we should write/discuss more on how to handle these things. What versions are supported, what do we consider "worthy" of the advisory. For example, it's often that we update packages due to some low CVE that has no impact on our project. 

 I quickly had to check https://thanos.io/tip/thanos/security.md/ again and I was actually surprised by the supported versions.

Perhaps you also have an idea on this?

**Comment by nfoonf** [comment]
I think the main info to be in an advisory is 

- affected supported versions
- fixed versions
- CVE reference
and thats probably it.

Mostly a security mailinglist serves the purpose of alerting Ops-Engineers not  to discuss issues. So noone besides the Dev-Team needs to be allowed to write to it. Often People plug this kind of lists directly into their Ticket-System (I for example, automatically open a priority Ticket for many vendor-issued security advisories.) so a good amount of auto-respond mail will come back from subscribers and it is totally okay, to drop incoming mail completely, imho.
