### ISSUE TITLE
Compactor: stuck after no space left on the device

### ISSUE THREAD

**Issue by Antiarchitect** [thanos-io/thanos#4920]
I'm running the 0.23.1 Thanos Compactor (bitnami image) inside K8s with a persistent volume of 200Gi size and still having no space left on the device error periodically. 
The most depressive part is that it seems the Compactor doesn't crash but frees some space and stops compacting after that.

Here are the logs of the Compactor currently stuck: https://gist.github.com/Antiarchitect/1bd60e144dd644ade064e143321d5cb8

**Comment by GiedriusS** [comment]
Could you please upload the goroutine dump when this situation occurs?

**Comment by yeya24** [comment]
`level=error ts=2021-12-02T13:38:12.414076829Z caller=compact.go:480 msg="critical error detected; halting" err="compaction: group 0@10167818604089879119: compact blocks [/data/compact/0@10167818604089879119/01FMBWX95ZNDNV95J0F7Z04SC6 /data/compact/0@10167818604089879119/01FMGTV4MJ9X8TTM8SGCCCK5X7 /data/compact/0@10167818604089879119/01FMNZKRJMZ3HZR0SMZKXCHJF6 /data/compact/0@10167818604089879119/01FMVB88HCGFWRNFJ1YE3QT5MM /data/compact/0@10167818604089879119/01FN094YHT320ZBVW8HPHGQ709 /data/compact/0@10167818604089879119/01FN5DY6WXGR0EWS6PB1QJFPD7 /data/compact/0@10167818604089879119/01FNAK34111D8WTN2R1BQYH819]: 3 errors: populate block: write chunks: preallocate: no space left on device; sync /data/compact/0@10167818604089879119/01FNXKSG88Z0W91QE6W220CW4J.tmp-for-creation/chunks/000154: file already closed; write /data/compact/0@10167818604089879119/01FNXKSG88Z0W91QE6W220CW4J.tmp-for-creation/index_tmp_p: no space left on device"
`
Compactor halted and the log mentioned that. This is an expected behavior and you should have a alert for compactor halting.

**Comment by Antiarchitect** [comment]
@yeya24 But the container has not restarted. And how much space should I give to the Compactor  to avoid this?

**Comment by GiedriusS** [comment]
You typically don't want to restart because Compactor will try to do this over and over if you don't have persistent storage, and it will lead to a huge bill for your remote object storage. It is recommended to have at least the size of sum of the smallest blocks in your compaction group + the size of the biggest block in your compaction group.

**Comment by GiedriusS** [comment]
https://github.com/thanos-io/thanos/issues/3405, https://github.com/thanos-io/thanos/pull/1550, and other issues are related
