### ISSUE TITLE
Automatic update of Busybox sha.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#4949]
We use ` quay.io/prometheus/busybox@sha256:${BASE_DOCKER_SHA}` as base image. We pin SHA so we now exactly what SHA is running for each docker tag of Thanos image.

Unfortunately, quay kills old SHAs very often and apparently Prometheus busybox is upgraded often too.

Let's automate this process so PR with new sha is proposed once some interval. 

AC:
* We no longer need to manually hardcode and change base image SHAs for Prometheus busy box as explained [here](
https://github.com/thanos-io/thanos/blob/c7a44e23febe94f7f1b290c18fe778bf72cd01fd/Makefile#L15)

**Comment by matej-g** [comment]
We had a small discussion on the Slack channel (https://cloud-native.slack.com/archives/CL25937SP/p1639582762123800) and it came up to couple of suggestions:
- Since it looks like we're currently always forces to use the `latest` image (since there's only that image tag in the https://quay.io/repository/prometheus/busybox?tab=tags repository), one idea was to - 1) _not_ pin the SHA, but get it on-the-fly from the `latest` image for both architectures; 2) include this information as a Docker label on the image
- Move to another base image which would have multiple version tags available (not only `latest`) and truly pin to the SHA which we want to use

**Comment by wiardvanrij** [comment]
At the moment working on this

**Comment by matej-g** [comment]
@wiardvanrij  I think it finally clicked for me why we cannot do it without pinning in the repository, since then whichever version / commit we're building the Thanos image for, we're always on `latest` BusyBox image - but it seems if the old BusyBox images do not exist after `latest` is overwritten, realistically we're unable to build with those non-`latest` base images since they are not available in the repo.

Anyways, long story short, having automatic PRs that would periodically sink the SHA sounds simpler and more straightforward way to go :+1:

**Comment by wiardvanrij** [comment]
> 

Awesome! :D Yea I can explain this rationale later on, I got to go now, will update my PR later with exactly that. Also cheers for working together on this 👍

**Comment by GiedriusS** [comment]
Can we close this now? (:

**Comment by GiedriusS** [comment]
https://github.com/thanos-io/thanos/pull/4965 fixed this.

**Comment by wiardvanrij** [comment]
Oh didn't got your previous reply.. but yeah 👍
