### ISSUE TITLE
Get thanos fails- build issue

### ISSUE THREAD

**Issue by sunkadavar** [thanos-io/thanos#5021]
**Thanos, Prometheus and Golang version used**:
Thanos version: latest
Go: go version go1.17.5 linux/amd64

**Object Storage Provider**:

**What happened**:
go get github.com/thanos-io/thanos/cmd/thanos
The above thanos install fails with below error.
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
github.com/thanos-io/thanos/pkg/extkingpin
../go/pkg/mod/github.com/thanos-io/thanos@v0.24.0/pkg/extkingpin/app.go:91:5: app.UsageFuncs undefined (type *kingpin.Application has no field or method UsageFuncs)
github.com/cortexproject/cortex/pkg/chunk/cache
../go/pkg/mod/github.com/cortexproject/cortex@v1.10.1-0.20211124141505-4e9fc3a2b5ab/pkg/chunk/cache/memcached_client.go:144:19: newClient.Client.DialTimeout undefined (type *memcache.Client has no field or method DialTimeout)

**What you expected to happen**:
go get github.com/thanos-io/thanos/cmd/thanos
should install thanos on my machine.

**How to reproduce it (as minimally and precisely as possible)**:
Install go version (*mentioned above) and run below command
github.com/thanos-io/thanos/cmd/thanos

**Full logs to relevant components**:

**Anything else we need to know**:
go install: github.com/thanos-io/thanos/cmd/thanos@latest (in github.com/thanos-io/thanos@v0.24.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.

**Comment by wiardvanrij** [comment]
`go get` is deprecated and unfortunately, the consensus seems to be that `go install` will never support replaces in `.mod` files. We absolutely need those replacements in order to have a non-blocking flow to continue the development of Thanos. 
I also don't think using go get/install methods is the preferred way to install Thanos. We provide the binaries, container images, and various tools in the Makefile to support your needs (i.e. `make build`). 

If there is a specific use-case, I'm happy to hear you out why this is needed though :)

**Comment by wiardvanrij** [comment]
Aha, I think we should update those docs! Thanks :)

**Comment by wiardvanrij** [comment]
Feel free to re-open this if you have any questions
