### ISSUE TITLE
Move object store client implementations out of sidecar binary

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#505]
Related discussion: https://github.com/improbable-eng/thanos/pull/500#discussion_r214356163

Currently we allow adding new obj store support by implementing `objstore.Bucket` interface and built it with Thanos sidecar. The detailed step to add new storage client is available here: https://github.com/improbable-eng/thanos/blob/master/docs/storage.md

This has following, negative consequences:
- Adding lot's of new Golang dependencies, potentially triggering dependency hell and lock in.
- Each client is quite different in configuration, and as https://github.com/improbable-eng/thanos/pull/500 shows, there is no way to create unified set of flags that works for all (despite the fact we looked on just 3 providers(!) ). Mitigation in form of custom yaml per client is not great -> It makes it even harder to discover what are configuration options.
- We end up maintaining the custom providers (and it's impossible, as usually we don't have access to the storage itself to test it!) 
- Binary size increases

**Acceptance Criteria:**
* Creating detailed design proposal for this
* Define flexible Push API that will allow users for implementing provider code in separate binaries.
  * Potentially create stick to S3 API for easier provider implementation (maybe gRPC S3?)
  * Alternative use go plugins.
* Potentially moving GCS and S3 for it.
* Maintain some up-to-date list of maintained provider codes.

**Comment by Bplotka** [comment]
Other option: [go plugins](https://golang.org/pkg/plugin/)

**Comment by vglafirov** [comment]
I think creating yet another set of microservices will be even worse, unless we completely moving them out from thanos repo and give all responsibility to actual maintainers. I like an idea of using Golang plugins, but never used them though.

**Comment by Bplotka** [comment]
> unless we completely moving them out from thanos repo and give all responsibility to actual maintainers. 

Yes, that's the main goal and advantage.

With go plugins we could potentially move tham away of thanos repo, but that would be extremely bad as thanos would crash because of badly maintained plugins.. so there is noobvious separation of who is to blame of error. It might be just hard to tell who is responsible for crash (: If we decide for go plugins and keeping them in same repo we have still issues:
- we need to care about dependencies
- we need to care how to pass configuration
- we cannot block from injecting plugins out of band

And I feel we could have problems on shared deps anyway for plugins, but not sure how that part works (:

**Comment by vic3lord** [comment]
I'm not sure it helps to the discussion but I really like the way Google took with GCK (Go Cloud Kit): https://github.com/google/go-cloud
