### ISSUE TITLE
Make it easier to pass documentation checks, especially for new users

### ISSUE THREAD

**Issue by wiardvanrij** [thanos-io/thanos#5282]
**What happened**:
A lot of PR's failing on something lame such as a whitespace. We also have multiple ways to format docs in our Makefile.

**What you expected to happen**:
That if ANY user makes a change, it should be VERY easy to contribute without having to figure special things out, install anything or get stuck in a PR

**How to reproduce it (as minimally and precisely as possible)**:
Make a doc change without applying any formatting and make a MR :)

**Anything else we need to know**:

I will be picking this up.

**Comment by matej-g** [comment]
What special things exactly need to be figured out by contributors? Doing `make docs` should be all that's required to generate and format the documentation properly and pass the PR checks. I'm still more conscious about [failing link checks](https://github.com/thanos-io/thanos/issues/4732), at least anecdotally that seem to cause most doc check failures.

**Comment by wiardvanrij** [comment]
We have `make docs`, `check-docs`, `docs` and `format`. 
You say `make docs` but that does not do `scripts/cleanup-white-noise.sh` and (I think) the pipeline does. 

I also had a clean setup, in which I also was missing bin's when I ran some make commands for it. I think it was something with MDOX. 

---

In general I don't see that many contributions in our docs and when I do see them, they are never ok. Either due to the failing link check like you mentioned or a missed format that has not been done. I want it to be easier and more accessible. Someone that has never used Make or contributed before, should have a very easy time to help contribute :)

**Comment by matej-g** [comment]
I agree we should it make as easy as possible for docs contributors as well, perhaps having clear instructions in `CONTRIBUTING.md` would help.

There are multiple commands, but IMHO all of them make sense and do different things:
- `make docs` generates, formats and cleans up white noise
- `make check-docs` generates, formats, cleans up white noise _and_ checks (since it can be annoying to wait on link check results - it takes forever - to skip the check, you can use `make docs`)
- `make changed-docs` does same as above, but just for changed docs (saving time, again)
- `make format` formats code

It really should be as easy as running `make docs`, or optionally `make check-docs`, to get passing docs.

**Comment by wiardvanrij** [comment]
But @matej-g , you forget it's easy for you and you are a smart engineer with many years of experience :)

I'm not planning to flip everything around, if it means we update the readme or whatever, that's a solution as well! I just wanted to place some dedicated time into this to improve it.

**Comment by matej-g** [comment]
Awesome, sorry for the lag, I appreciate the doc improvements!
