### ISSUE TITLE
Deduplication functionality is not available through gRPC

### ISSUE THREAD

**Issue by GiedriusS** [thanos-io/thanos#549]
We only enable deduplication when a new querier is created because of a request that comes through the web UI: https://github.com/improbable-eng/thanos/blob/242f5a4099327d10474074f5b6d7824576feecfc/pkg/query/api/v1.go#L462-L468
However, there is no way to get this kind of functionality through the `service Store` interface through gRPC. Perhaps a optional boolean flag should be added to the `SeriesRequest` message which would indicate that the client wants the deduplicated data.

**Comment by bwplotka** [comment]
This is intentional as the deduplication is done only on querier. Making deduplication part of StoreAPI is tricky, as it does not make sense to deduplicate for some of storeAPI implementations like `sidecar` or potentially `ruler`. Having just one component in stack that does it, makes it easier to think about.

What is the use case?

**Comment by GiedriusS** [comment]
The goal is to be able to re-use the same code that uses gRPC that we use for benchmarking the performance of our Thanos deployment units. Plus, I thought that maybe there is some value in unifying the API that Thanos has in gRPC and in the regular HTTP calls.

**Comment by bwplotka** [comment]
Not really as again - deduplication does not make sense for some implementation of StoreAPI.

We could consider it but.. Is this blocking you or rather nice to have?

**Comment by GiedriusS** [comment]
Certainly not blocking anything, just a thing that would be nice to have IMHO.
