### ISSUE TITLE
Docs: Document hidden flags

### ISSUE THREAD

**Issue by matej-g** [thanos-io/thanos#5835]
I have noticed there is zero mention of hidden flags in our documentation. Although we hide behind them unstable features that are not meant for stable environments, they should still be documented in the `.md` files and on the website (perhaps in a separate block).

**Comment by Hyperbolic007** [comment]
Hey @matej-g I want to work on this issue. Can you please tell where should I study about these hidden flags.

**Comment by fpetkovski** [comment]
I thought the idea of hidden flags is to not have them documented so that we can try them out ourselves before exposing them to users 🤔 .

**Comment by aniketdogra07** [comment]
hlo @matej-g i can work on this issue can u please provide me .I can suggest some points that we can do in this issue is :
To document hidden flags in your documentation, we can include a separate section or block in your documentation specifically for these flags. In this section, you should describe the purpose of each flag, how to enable and use it, and any potential risks or limitations associated with using it.

It's also a good idea to include a disclaimer or warning about the use of hidden flags in stable environments, as they may be unstable and could potentially cause problems.

**Comment by hackeramitkumar** [comment]
@matej-g it's a good idea to document hidden flags. I would like to document them. Can you please assign it to me ?

**Comment by egomezbpedro** [comment]
Hi @matej-g,

I've been reviewing good first issues to get a grasp of the project. In this particular I do not think that it is clear what are the hidden flags that you are pointing. IDK if you have already discussed about this with the previous commenters, but perhaps you could share a bit more insights about them (if they are still a thing). 

This will surely help me and any other enthusiast that might find this good-first-issue.

cheers

**Comment by matej-g** [comment]
Hey, sorry I haven't updated this issue. After more thought, I think @fpetkovski is right, since those flags enable experimental features that should not be published before they are stabilized. Users who know what they are doing and want to know the usage of the flags can look for the documentation in the code.

I will close this for now.
