### ISSUE TITLE
 how to set thanos compactor params

### ISSUE THREAD

**Issue by itarch** [thanos-io/thanos#639]
Hi all

I have setup a thanos cluster around Prometheus (visualized [here](https://github.com/minio/minio/issues/6824#issuecomment-439388456)). It is just a lab to come in and understand how things work. My PROM Instances are configured to keep data only 25 hours, however I see nearly 36 hours, don’t know why, but this is not my question. Further, data will be backup by Thanos sidecar in Minio where data older than 25 days have to be deleted manually. Since it is a lab I delete (with minio cli) data older 10 days.  

MY QUESTION:
I want to make use of “Thanos Compactor”. What are the right values of the three following params when I want to keep 4 days uncompressed, between 4th-6th day 5min compaction and longer than 6 days 1hour compaction. 
--retention.resolution-raw=4d
--retention.resolution-5m=2d or 6d
--retention.resolution-1h=?

MY ENVIRONMENT:
OS VERSION
$ uname -a
Linux XXXXXX 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

THANOS VERSION:
$ ./thanos --version
thanos, version 0.1.0 (branch: master, revision: 3bb4076af3fcf6d166d6690581af22cee086cc8d)
  build user:       root@PROMC11
  build date:       20181110-16:43:16
  go version:       go1.10.4

**Comment by bwplotka** [comment]
Why do you use Thanos compactor if we you want only 4 days of data?

```
```

**Comment by bwplotka** [comment]
Why do you use Thanos compactor if you want only 4 days of data? 
The whole global compaction and long term storage is designed for _years_ of data. For example no downsampling will happen before the object will be compacted to 40h, so not until 2d intial days.

For your setup you would be probably fine with just sidecars and querier, have you thought about it?

Otherwise, yea we have to document (and test those better) as this retention is not strict retention. We delete only full blocks that will happen to have minTime older than specified retention. This means that e.g for 4d retention the actual data will be cover `[(t-6d)  (t-4d)]` time range, because at 4d time, the block will be 2d wide.

**Comment by itarch** [comment]
@bwplotka thank you for feedback

of course, i have no doubt about thanos capabilities to manage data years and more.

In a lab environment i have to keep things short to understand how to config those stuff later in real enterprise environment.

**Comment by bwplotka** [comment]
Stale issue, let us know if you still need help (:
