### ISSUE TITLE
How to reduce the network traffic generated by the s3 store initialization process

### ISSUE THREAD

**Issue by zhujinhe** [thanos-io/thanos#664]
It seems thanos store loads all s3 bucket files during initialization and then generate index.cache.json(aboud 9M in my case) . 
This will take lots of network traffic in large environment.
Can we also put index.cache.json files in s3 bucket to reduce network traffic of initialization?

version: v0.2.0-rc.0-lazy-postings
thanos, version 0.1.0 (branch: store-profile, revision: ca11572099cb4f64c916c13c7b411b97cccff24a)
  build user:       bartek@bartek-lin-fgzbqq2.corp.improbable.io
  build date:       20181111-01:16:32
  go version:       go1.10

**Comment by bwplotka** [comment]
Hey, why putting index.cache.json in s3 bucket will help with you? We need to have this on disk for fast lookup. (this is our block scope index). We could precompute this cache though, so it would save some CPU time, but I think the most time is spend on net traffic.

Anyway, feedback welcome how to improve this (:

**Comment by adaam** [comment]
Here has same question.
In my case, we have nearly 500GB Prometheus data in S3 bucket. And it will be more in future. ( We generate ~ 8GB prometheus data per day )
When thanos store start, thanos will download nearly 20GB data to generate index.cache.json in our case, download and process time about 5 minutes in r4.xlarge.

In our case, we might not always run thanos store, we just need it when we want to query metrics which older than 3 months for troubleshoot.
It will be cost if we need to download 20GB or more data from S3 at initialization process at thanos store.

My thought is, if index.cache.json never change after it generated, it will be helpful if we can generate the file when we upload/backup to S3. 
So we just need to download index.cache.json and meta.json from each folder. It save lots of time and bandwidth.

**Comment by bwplotka** [comment]
Sure, but only if `index.cache.json` is much smaller then index itself. Can you compare index.cache.json vs index sized for one of you bigger block?

Anyway just downloading those JSONs instead of computing those makes sense.Compactor could be generating those after compaction just fine.

**Comment by adaam** [comment]
Why we need this is because we found if --data-dir already have index.cache.json in it, it won't pull much data every time.

BTW, does this file can be create when thanos backup data to S3 ? In our case, we don't use compactor to reduce file size, we want to keep data as much as we can, then we won't miss any detail from our metrics.

Below if compare between index v.s. index.cache.json
-rw-r--r-- 1 pmm pmm 2.3G Dec  9 03:08 01CY8ENVYQ5Y0483SH1W5QBT0W/index
-rw-r--r-- 1 pmm pmm 2.3G Dec 15 21:08 01CYSTVPHVKSGPGJ41YV8ZXQHZ/index
-rw-r--r-- 1 pmm pmm 113M Dec 20 03:00 01CZ4RX5F2FN7MX6RKBTDGXC5E/index
-rw-r--r-- 1 pmm pmm  57M Dec 20 05:00 01CZ4ZR54GJC7PAV065S9NY6X3/index

-rw-r--r-- 1 root root 1.5M Dec 19 08:56 01CY8ENVYQ5Y0483SH1W5QBT0W/index.cache.json
-rw-r--r-- 1 root root 1.5M Dec 19 08:56 01CYSTVPHVKSGPGJ41YV8ZXQHZ/index.cache.json
-rw-r--r-- 1 root root 1.5M Dec 20 03:02 01CZ4RWDWHDDZ7R17Q7Q4MN11G/index.cache.json
-rw-r--r-- 1 root root 1.5M Dec 20 05:02 01CZ4ZR54GJC7PAV065S9NY6X3/index.cache.json

**Comment by bwplotka** [comment]
> BTW, does this file can be create when thanos backup data to S3 ? In our case, we don't use compactor to reduce file size, we want to keep data as much as we can, then we won't miss any detail from our metrics

Compactor does not drop any data. It just compress blocks better for more efficient lookup. Do you mean  that you don't use compactor which is required for efficient block fetching? Then indeed store gateway will take ages to start up as it has multiple of super small blocks. (:

**Comment by paulopontesm** [comment]
This dosen't doesn't solve load times, but if you are in AWS maybe VPC endpoints can help with costs:
https://medium.com/nubego/how-to-save-money-with-aws-vpc-endpoints-9bac8ae1319c

**Comment by adaam** [comment]
After use compactor, I drop data for store and restart it, it still pull nearly 23 GB data from S3.
Seems compactor not help in this case. but it truly compact data in my S3, I can see folder number fewer before I run compactor.

BTW, I know by default, compactor will set all --retention.resolution to 0d, which mean it will disables this retention, but i still saw message from caller=downsample.go, say it running downsampling process. Is it normal?
Because I'm trying to keep our data as detail as we can, don't want to downsample any data in our case. In my case, we use PMM (backend data store is prometheus) to monitor our database every 3 seconds, to see any peak usage in any time, for DB it may just heavily use CPU in few seconds.
After downsample, we will hard to know how long the query effect our server.

**Comment by FUSAKLA** [comment]
The `--retention.resolution` flag allows you to specify for how long to keep the data in raw, 5m and 1h resolution. Default value is `0d` which means do not drop any data. But the down-sampling still happens that's why you see the down-sampling message in log. I'm not aware of possibility to disable data down-sampling in compactor but when you query the Query node you can specify if you want to use down-sampled data or not so if you restrict the Query to use only the raw data with the `&max_source_resolution=0s` param to the REST API than you have nothing to worry about but this should be default IIRC. You can contrarily enable the auto down-sampling using the `--query.auto-downsampling` flag for query node.

**Comment by adaam** [comment]
I noticed that even all --retention.resolution setting to 0d. Store still pull data back, maybe this step can be skip to save some cost?

Thank all of you made this tool, this tool save me bunched of time.

**Comment by xjewer** [comment]
+1 for having `index.cache.json` in object storage, as blocks are immutable:

index file: 
```
19.9887986844G 1 objects s3://thanos-production/01CY1A7Y5GGY1HBMRDDPA7ANKJ/index
```

cache file:
```
63M	01CY1A7Y5GGY1HBMRDDPA7ANKJ/index.cache.json
```

in startup time it has to download huge amount of data just in order to make a cache

**Comment by bwplotka** [comment]
Sorry for lag (: 

The compactor is capable to generate index files for compacted blocks with `--index.generate-missing-cache-file` flag. Additionally, the persistent volume should ensure we only generate this index file for new, not seen blocks on startup. (: Hope that helps.

**Comment by balusarakesh** [comment]
Hi @adaam
I see that you use pmm prometheus with thanos, right now I'm facing an issue with `compaction` because the prometheus in pmm by default sets `storage.tsdb.min-block-duration` and `storage.tsdb.max-block-duration` to different values `2h` and `3d`. This is throwing an error in thanos sidecar like below which is not starting thanos sidecar at all.
How did fix this problem?
```
level=error ts=2020-03-29T00:23:12.266083305Z caller=main.go:199 msg="running command failed" err="validate Prometheus flags: found that TSDB Max time is 3d and Min time is 2h. Compaction needs to be disabled (storage.tsdb.min-block-duration = storage.tsdb.max-block-duration)"
```

**Comment by bwplotka** [comment]
Run https://thanos.io/components/compact.md/

Also @balusarakesh please ask on Slack next time instead of commenting random GitHub issue please (:

**Comment by kartik-moolya** [comment]
> This dosen't doesn't solve load times, but if you are in AWS maybe VPC endpoints can help with costs:
> https://medium.com/nubego/how-to-save-money-with-aws-vpc-endpoints-9bac8ae1319c

Have you used VPC endpoint with Thanos ? Do you have a reference please?
