### ISSUE TITLE
Feature Request: Allow deduplication to favour a replica label pattern

### ISSUE THREAD

**Issue by roganartu** [thanos-io/thanos#707]
We run a Prometheus cluster with short-term retention nodes and long-term retention nodes. All nodes scrape everything, but the short-term nodes scrape at a higher frequency (eg: 30s) and retain for less time (eg: days), while the long-term nodes scrape at a lower frequency (eg: 5m) and retain for longer (eg: months/years).

We use Thanos with deduplication as a query proxy for this setup, but it's not really designed to support it so we naturally encounter some undesired behaviour. The goal of using Thanos in this design is to allow us to achieve the following query behaviour:
- If present, always prefer datapoints from the short-term nodes as they are more granular
- Otherwise, use datapoints from the long-term nodes (eg: when a short-term node was down or the query is historic and targeting a range before the short-term node has data.

Using deduplication as it currently exists in Thanos generally results in the short-term nodes being favoured in most scenarios, but when those nodes have gaps the entire query ends up falling back to the long-term node instead of just the missing ranges as desired.

eg:
Without deduplication:
<img width="1914" alt="screen shot 2019-01-03 at 10 20 41 am" src="https://user-images.githubusercontent.com/1133705/50645357-fe448780-0f38-11e9-88ba-1f382fb80c96.png">
You can see that there is a gap in the short-term node data, but in the second half of the graph the gap resolves and the granular data from that node returns.

With deduplication:
<img width="1914" alt="screen shot 2019-01-03 at 10 20 58 am" src="https://user-images.githubusercontent.com/1133705/50645412-1ddbb000-0f39-11e9-8bb9-1a585ab41772.png">
Here (as expected since it's designed for true-replicas and not varying-granularity "replicas") we see Thanos favour the long-term node due to the way the penalties and earliest timestamps work. I would like to be able to configure Thanos to always favour the short-term node when it has datapoints, so that the graph instead has all the red portions from the first image, and only falls back to the green when the red is not present.

I'm happy to have a crack at implementing this if there is support for it. I'd be ok with a simple preference pattern (where it is a simple yes/no preference), but I could also see this being a priority implementation (eg `--deduplication.priority node1,100 --deduplication.priority node2,50 --deduplication.priority node3 25`) to allow more flexibility but that's obviously more complex.

**Comment by roganartu** [comment]
What the previous query looks like with the short-term node set to a higher priority while running the above PR:
<img width="1920" alt="screen shot 2019-01-08 at 11 41 03 am" src="https://user-images.githubusercontent.com/1133705/50845895-92489180-1333-11e9-8d23-a6e4ef53a2c8.png">

**Comment by bwplotka** [comment]
What is the green line in your first screenshot?

Thanks for this, overall:
> while the long-term nodes scrape at a lower frequency (eg: 5m) and retain for longer (eg: months/years).

This is quite unique design. The problem with this "artificial" downsampling is that it is not really accurate. Because you just gather less samples, you might totally miss spikes for gauges and time of spikes for counters. I would recommend gathering data with same interval and use automatic Thanos downsampling that will preserve methematic accuracy (max, avg, sum, count will give you correct answers). The thing is that collecting more samples is quite easy to compress (easily compressible dimension), so should not be that problematic.

> I'm happy to have a crack at implementing this if there is support for it. I'd be ok with a simple preference pattern (where it is a simple yes/no preference), but I could also see this being a priority implementation (eg --deduplication.priority node1,100 --deduplication.priority node2,50 --deduplication.priority node3 25) to allow more flexibility but that's obviously more complex.

Thanks! I think we would be happy to fix your situation, but rather givin different use case. I can imagine case of rolling upgrade when you change some series from long intervals to very short ones and rollout one replica after another. You would like to get all data, and prefer this with short interval I suppose. 

However adding config complexity of setting each priority label sounds quite large as you need to plumb it trough different layers. Size of your PR kind of confirms this (:   

Wonder if there is a way to detect and prefer short intervals always automatically, without external configuration. What do you think? Sounds possible in theory.

**Comment by bwplotka** [comment]
Yup, some rolling behavior would work. Let's experiment with different behaviors. We can always have different types of deduplication to ensure no regression is done for users who get used to old one.
