### ISSUE TITLE
query: optimizations by adding filtering method in proxy.go

### ISSUE THREAD

**Issue by sanamana** [thanos-io/thanos#879]
**Thanos, Prometheus and Golang version used**

Thanos v0.2.1
Golang 1.11.2
Prometheus 2.7.1

**What happened**
All of our data fits in about 600 storage instances and there are 600 sidecars. There is a strong likelihood for this number of grow as traffic grows. We have a way of mapping a query to the list of store instances which hold data for that query. But there is no way to filter the stores other than changing the selector labels passed in the query. 

**Proposal**
Allowing registering a function that can filter stores list while creating ProxyStore instance and using this function in Series() method of ProxyStore.

What does the community think about this proposal.

**Comment by bwplotka** [comment]
Hi! 

That's a lot of Prometheus instances indeed! (: 

First of all you might be hiting this bit: https://github.com/improbable-eng/thanos/issues/751 (re querier memory consumption/concurency) 

But I think you are asking about custom filtering. So first of all:
1. What would you put into this custiom function? What do you mean by registering a function? What should be implemented there?
2. We chose label selecting as the native way of filtering in Prometheus world. It works extremely well and it's quite clean and understanable in both usage and implementation. If you really don't want to educate your users on how to use query to not query ALL stores, there is a simple solution most companies uses: middleware/proxy that injects labels for certain users depending on application logic (e.g different project/team can touch only some storeAPIs). Would like some proxy like this being available in Thanos Querier itself? You might be able to do something like this using https://github.com/metalmatze/prom-label-proxy as well. 
3. You can also filter out by having separate Thanos Querier to each set of sidecars/stores. You can then have federated Thanos Querier on top of it only for admins, etc. 


Having that said 2 & 3 should solve all use cases, but please let us know if it's otherwise in your case. Also feel free to join slack and start some discussion there - we would like to know more details about your use case! (:

**Comment by sanamana** [comment]
Thank you for the feedback.
#1. In my mind the custom function signature would look like this func(r *storepb.SeriesRequest, stores []Client) ([]Client, error)

#2. I have briefly looked at injecting necessary labels using a middleware-proxy. The way it would work in our case is that the same series data can be present in multiple stores. Each store is identified uniquely not by one label, but by multiple labels. Say a store is {shard, replica, cluster, namespace, partition} and we have a list of these.  I would need to re-write the query and inject specific combination of store label information. Also the proxy is another component that we have to keep track of and adds another hop.

#3. Our stack does not allow us to go this route. We have a prometheus tsdb engine fronted by ingress handlers. The logic to scale horizantally is part of ingress handlers and they can spray the same data to different tsdb servers. The determination of data locality is done by a separate layer. We want to use this layer in thanos querier using a custom function.
